In [ ]:
import pandas as pd

In [ ]:
df=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_sch_course_offers.parquet")
df
df.drop_duplicates()

,course_id,course_credits,part_id,department_id,faculty_id,allow_register
0,88.111,3.0,20050.0,37.111,7.111,NaN
1,88.111,3.0,20051.0,37.111,7.111,NaN
2,88.111,3.0,20052.0,37.111,7.111,NaN
3,88.111,3.0,20053.0,37.111,7.111,NaN
4,88.111,3.0,20060.0,37.111,7.111,NaN
...,...,...,...,...,...,...
137894,1453.111,3.0,20250.0,NaN,NaN,NaN
137895,1453.111,3.0,20251.0,NaN,NaN,Y
137896,1453.111,3.0,20252.0,NaN,NaN,NaN
137897,1453.111,3.0,20253.0,NaN,NaN,NaN
137898,1453.111,3.0,20254.0,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 137899 entries, 0 to 137898
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   course_id       137899 non-null  float64
 1   course_credits  137899 non-null  float64
 2   part_id         137899 non-null  float64
 3   department_id   122670 non-null  float64
 4   faculty_id      122670 non-null  float64
 5   allow_register  31947 non-null   str
dtypes: float64(5), str(1)
memory usage: 6.4 MB

In [4]:
df1=df.drop(columns=['allow_register'],)
df1.dropna()

        course_id  course_credits  part_id  department_id  faculty_id
0          88.111             3.0  20050.0         37.111       7.111
1          88.111             3.0  20051.0         37.111       7.111
2          88.111             3.0  20052.0         37.111       7.111
3          88.111             3.0  20053.0         37.111       7.111
4          88.111             3.0  20060.0         37.111       7.111
...           ...             ...      ...            ...         ...
136827   1437.111             2.0  20250.0         35.111      34.111
136828   1437.111             2.0  20251.0         35.111      34.111
136829   1437.111             2.0  20252.0         35.111      34.111
136830   1437.111             2.0  20253.0         35.111      34.111
136831   1437.111             2.0  20254.0         35.111      34.111

[122670 rows x 5 columns]