In [40]:
import pandas as pd 
df=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_acd_degree_course.parquet")

In [41]:
df.head(20)
# df.info()

,degree_course_id,course_id,course_name_sl,degree_id,degree_name_sl,year_order,semester_order,required_credits,course_credits,active,credits_count,faculty_id,requirement_type_id,requirement_type_sl,req_degree_id
0,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN
1,1.111,917.111,الكيمياء الحيوية,17.111,الصيدلة,3.0,1.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
2,2.111,923.111,الكيمياء الحيوية التطبيقية,17.111,الصيدلة,3.0,2.0,NaN,3.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
3,3.111,908.111,الإحصاء الحيوي,17.111,الصيدلة,2.0,1.0,NaN,2.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
4,4.111,891.111,البيولوجيا النباتية,17.111,الصيدلة,1.0,1.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
5,5.111,907.111,تجارة الأدوية,17.111,الصيدلة,2.0,1.0,NaN,2.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
6,6.111,888.111,الكيمياء العامة,17.111,الصيدلة,1.0,1.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
7,7.111,895.111,الكيمياء العامة والتحليلية,17.111,الصيدلة,1.0,2.0,NaN,3.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
8,8.111,897.111,الكيمياء العضوية الأساسية,17.111,الصيدلة,1.0,2.0,NaN,3.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
9,9.111,902.111,الكيمياء العضوية الصيدلانية (1),17.111,الصيدلة,2.0,1.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
10,10.111,909.111,الكيمياء العضوية الصيدلانية (2),17.111,الصيدلة,2.0,2.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
11,11.111,903.111,التحليل الكمي الصيدلاني,17.111,الصيدلة,2.0,1.0,NaN,5.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
12,12.111,910.111,التحليل الآلي,17.111,الصيدلة,2.0,2.0,NaN,3.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
13,13.111,919.111,تقنيات الفصل (1),17.111,الصيدلة,3.0,1.0,NaN,2.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
14,14.111,925.111,تقنيات الفصل (2),17.111,الصيدلة,3.0,2.0,NaN,2.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
15,15.111,926.111,الكيمياء الدوائية (1),17.111,الصيدلة,3.0,2.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
16,16.111,930.111,الكيمياء الدوائية (2),17.111,الصيدلة,4.0,1.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
17,17.111,943.111,تصميم الدواء,17.111,الصيدلة,5.0,1.0,NaN,3.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
18,18.111,944.111,السيطرة النوعية الكيميائية,17.111,الصيدلة,5.0,1.0,NaN,3.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
19,19.111,937.111,الصيدلة السريرية,17.111,الصيدلة,4.0,2.0,NaN,3.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111

In [42]:
df.head(20)
needed_column=["degree_course_id", "course_id", "degree_id", "course_name_sl", "degree_name_sl", "course_credits", "requirement_type_id", "requirement_type_sl"]
df1=df[needed_column]

In [43]:
df1

,degree_course_id,course_id,degree_id,course_name_sl,degree_name_sl,course_credits,requirement_type_id,requirement_type_sl
0,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.111,917.111,17.111,الكيمياء الحيوية,الصيدلة,4.0,5.0,متطلبات الشهادة الإجبارية
2,2.111,923.111,17.111,الكيمياء الحيوية التطبيقية,الصيدلة,3.0,5.0,متطلبات الشهادة الإجبارية
3,3.111,908.111,17.111,الإحصاء الحيوي,الصيدلة,2.0,5.0,متطلبات الشهادة الإجبارية
4,4.111,891.111,17.111,البيولوجيا النباتية,الصيدلة,4.0,5.0,متطلبات الشهادة الإجبارية
...,...,...,...,...,...,...,...,...
1695,1613.101,1095.000,3.111,NaN,هندسة البرمجيات ونظم المعلومات,NaN,1.0,متطلبات الجامعة الإجبارية
1696,1614.101,1096.000,3.111,NaN,هندسة البرمجيات ونظم المعلومات,NaN,1.0,متطلبات الجامعة الإجبارية
1697,1615.101,1097.000,3.111,NaN,هندسة البرمجيات ونظم المعلومات,NaN,1.0,متطلبات الجامعة الإجبارية
1698,1616.101,1163.101,3.111,NaN,هندسة البرمجيات ونظم المعلومات,NaN,5.0,متطلبات الشهادة الإجبارية
1699,1617.101,1164.101,3.111,NaN,هندسة البرمجيات ونظم المعلومات,NaN,5.0,متطلبات الشهادة الإجبارية

In [44]:
df1.isna().sum()
d=df1.drop(index=0,axis=0)

In [45]:
d.isna().sum()

degree_course_id        0
course_id               0
degree_id               0
course_name_sl         14
degree_name_sl          0
course_credits         14
requirement_type_id     0
requirement_type_sl     0
dtype: int64

In [46]:
d[d["course_credits"].isna()]
d.dropna(axis=0,inplace=True)

In [47]:
d.to_csv(r"D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_ACD_DEGREE_COURSE\v_acd_degree_course.csv",index=False)

In [48]:
D=pd.read_csv(r"D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_ACD_DEGREE_COURSE\v_acd_degree_course.csv")

In [49]:
D.info()

<class 'pandas.DataFrame'>
RangeIndex: 1685 entries, 0 to 1684
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   degree_course_id     1685 non-null   float64
 1   course_id            1685 non-null   float64
 2   degree_id            1685 non-null   float64
 3   course_name_sl       1685 non-null   str
 4   degree_name_sl       1685 non-null   str
 5   course_credits       1685 non-null   float64
 6   requirement_type_id  1685 non-null   float64
 7   requirement_type_sl  1685 non-null   str
dtypes: float64(5), str(3)
memory usage: 307.3 KB