In [1]:
import pandas as pd 
pd.set_option('display.max_columns',100)

In [2]:
df=pd.read_parquet(r'D:\AI\Real projects\Academic_Advisor\data\audit\after_fet_eng.parquet')

In [3]:
df.head()

,student_course_id,student_id,course_id,part_id,degree_id,faculty_id,grade_id,final_mark,course_credits,attempt_number,student_status_id,prev_gpa_points,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,semester_reg_credits,semester_reg_courses,semester_pass_credits,total_pass_credits,total_fail_credits,reg_total_semesters,start_level_name_pl,start_part_id,requirement_type_id,degree_requirement_credits_count,university_id,is_high_credit_course,over_policy_semester_credits,over_policy_semester_courses,exclude_over_policy_semester,is_extreme_fail_history,total_fail_credits_capped,is_interruption_semester,prev_semester_was_interruption,prior_interruption_count,consecutive_interruption_count,no_previous_progress,is_first_active_semester,is_first_row_in_timeline,last_valid_gpa_before_current_semester,prev_gpa_points_missing,prev_gpa_points_zero,prev_gpa_invalid_zero_case,prev_gpa_points_clean,prev_gpa_fill_source,prev_gpa_replaced_due_to_invalid_zero,prev_gpa_actual_zero_performance,model_prev_gpa,part_year,part_semester,start_year,start_semester,start_level_missing,start_level_ord,requirement_type_missing,degree_requirement_credits_count_missing,course_share_of_requirement,requirement_size_bucket,fail_credit_ratio_capped,degree_course_key
0,939272.111,10000.111,1016.111,20152,3.111,5.111,677.111,82,2.0,1,155348.111,2.41,2.36,2.41,6.0,17.0,18.0,6.0,18.0,17.0,0.0,2.0,First Year,20151,2,6,111,0,False,False,False,0,0.0,0,0,0,0,0,0,0,2.41,0,0,0,2.41,raw_prev_gpa,0,0,2.41,2015,2,2015,1,0,1,0,0,0.333333,small,0.0,3.111__1016.111
1,953865.111,10000.111,1017.111,20153,3.111,5.111,680.111,67,2.0,1,155349.111,2.36,2.25,2.39,12.0,35.0,9.0,3.0,9.0,35.0,0.0,3.0,Second Year,20151,2,6,111,0,False,False,False,0,0.0,0,0,0,0,0,0,0,2.36,0,0,0,2.36,raw_prev_gpa,0,0,2.36,2015,3,2015,1,0,2,0,0,0.333333,small,0.0,3.111__1017.111
2,1076397.111,10000.111,1019.111,20171,3.111,5.111,981.111,66,2.0,1,240678.111,2.17,1.76,2.28,27.0,80.0,17.0,6.0,17.0,80.0,0.0,6.0,Third year,20151,2,6,111,0,False,False,False,0,0.0,0,0,0,0,0,0,0,2.17,0,0,0,2.17,raw_prev_gpa,0,0,2.17,2017,1,2015,1,0,3,0,0,0.333333,small,0.0,3.111__1019.111
3,925010.111,10000.111,431.111,20152,3.111,5.111,677.111,83,3.0,1,155348.111,2.41,2.36,2.41,6.0,17.0,18.0,6.0,18.0,17.0,0.0,2.0,First Year,20151,3,65,111,0,False,False,False,0,0.0,0,0,0,0,0,0,0,2.41,0,0,0,2.41,raw_prev_gpa,0,0,2.41,2015,2,2015,1,0,1,0,0,0.046154,very_large,0.0,3.111__431.111
4,901340.111,10000.111,432.111,20151,3.111,5.111,681.111,61,4.0,1,155347.111,<NA>,2.41,0.0,0.0,0.0,17.0,6.0,17.0,0.0,0.0,1.0,First Year,20151,3,65,111,0,False,False,False,0,0.0,0,0,0,0,1,1,1,<NA>,1,0,0,0.00,zero_fallback,0,0,NaN,2015,1,2015,1,0,1,0,0,0.061538,very_large,0.0,3.111__432.111

In [4]:
df.shape

(727852, 61)

In [5]:
df.info()

<class 'pandas.DataFrame'>
Index: 727852 entries, 0 to 761345
Data columns (total 61 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   student_course_id                         727852 non-null  string
 1   student_id                                727852 non-null  string
 2   course_id                                 727852 non-null  str
 3   part_id                                   727852 non-null  string
 4   degree_id                                 727852 non-null  string
 5   faculty_id                                727852 non-null  string
 6   grade_id                                  727852 non-null  string
 7   final_mark                                727852 non-null  Int64
 8   course_credits                            727852 non-null  Float64
 9   attempt_number                            727852 non-null  Int64
 10  student_status_id                         727852 non-null  string
 11  prev_gpa_points                           636799 non-null  Float64
 12  gpa_points                                727852 non-null  Float64
 13  start_agpa_points                         727852 non-null  Float64
 14  start_total_in_courses                    727852 non-null  Float64
 15  start_total_in_credits                    727852 non-null  Float64
 16  semester_reg_credits                      727852 non-null  Float64
 17  semester_reg_courses                      727852 non-null  Float64
 18  semester_pass_credits                     727852 non-null  Float64
 19  total_pass_credits                        727852 non-null  Float64
 20  total_fail_credits                        727852 non-null  Float64
 21  reg_total_semesters                       725171 non-null  Float64
 22  start_level_name_pl                       727852 non-null  string
 23  start_part_id                             727852 non-null  Int64
 24  requirement_type_id                       726449 non-null  Int64
 25  degree_requirement_credits_count          726449 non-null  Int64
 26  university_id                             727852 non-null  string
 27  is_high_credit_course                     727852 non-null  int64
 28  over_policy_semester_credits              727852 non-null  boolean
 29  over_policy_semester_courses              727852 non-null  boolean
 30  exclude_over_policy_semester              727852 non-null  bool
 31  is_extreme_fail_history                   727852 non-null  int64
 32  total_fail_credits_capped                 727852 non-null  Float64
 33  is_interruption_semester                  727852 non-null  int64
 34  prev_semester_was_interruption            727852 non-null  int64
 35  prior_interruption_count                  727852 non-null  int64
 36  consecutive_interruption_count            727852 non-null  int64
 37  no_previous_progress                      727852 non-null  int64
 38  is_first_active_semester                  727852 non-null  int64
 39  is_first_row_in_timeline                  727852 non-null  int64
 40  last_valid_gpa_before_current_semester    629388 non-null  Float64
 41  prev_gpa_points_missing                   727852 non-null  int64
 42  prev_gpa_points_zero                      727852 non-null  int64
 43  prev_gpa_invalid_zero_case                727852 non-null  int64
 44  prev_gpa_points_clean                     727852 non-null  float64
 45  prev_gpa_fill_source                      727852 non-null  string
 46  prev_gpa_replaced_due_to_invalid_zero     727852 non-null  int64
 47  prev_gpa_actual_zero_performance          727852 non-null  int64
 48  model_prev_gpa                            633316 non-null  float64
 49  part_year                                 727852 non-null  Int64
 50  part_semester                             727852 non-null  Int64
 51  start_year                                727852 non-null  Int64
 52  start_semester                            727852 non-null  Int64
 53  start_level_missing                       727852 non-null  int64
 54  start_level_ord                           727852 non-null  int64
 55  requirement_type_missing                  727852 non-null  int64
 56  degree_requirement_credits_count_missing  727852 non-null  int64
 57  course_share_of_requirement               727852 non-null  float64
 58  requirement_size_bucket                   727852 non-null  string
 59  fail_credit_ratio_capped                  727852 non-null  float64
 60  degree_course_key                         727852 non-null  string
dtypes: Float64(14), Int64(9), bool(1), boolean(2), float64(4), int64(18), str(1), string(12)
memory usage: 422.8 MB

In [6]:
df['prev_gpa_points'].value_counts(dropna=False) ## <NA>    91053

prev_gpa_points
<NA>    91053
0.0     34418
2.5     12673
2.25    12457
2.75    11123
        ...
0.1        21
3.93       13
0.09       11
3.87        9
3.97        5
Name: count, Length: 391, dtype: Int64

In [7]:
df_zeor_gpa=df[df['gpa_points']==0]

In [8]:
df_zeor_gpa

,student_course_id,student_id,course_id,part_id,degree_id,faculty_id,grade_id,final_mark,course_credits,attempt_number,student_status_id,prev_gpa_points,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,semester_reg_credits,semester_reg_courses,semester_pass_credits,total_pass_credits,total_fail_credits,reg_total_semesters,start_level_name_pl,start_part_id,requirement_type_id,degree_requirement_credits_count,university_id,is_high_credit_course,over_policy_semester_credits,over_policy_semester_courses,exclude_over_policy_semester,is_extreme_fail_history,total_fail_credits_capped,is_interruption_semester,prev_semester_was_interruption,prior_interruption_count,consecutive_interruption_count,no_previous_progress,is_first_active_semester,is_first_row_in_timeline,last_valid_gpa_before_current_semester,prev_gpa_points_missing,prev_gpa_points_zero,prev_gpa_invalid_zero_case,prev_gpa_points_clean,prev_gpa_fill_source,prev_gpa_replaced_due_to_invalid_zero,prev_gpa_actual_zero_performance,model_prev_gpa,part_year,part_semester,start_year,start_semester,start_level_missing,start_level_ord,requirement_type_missing,degree_requirement_credits_count_missing,course_share_of_requirement,requirement_size_bucket,fail_credit_ratio_capped,degree_course_key
170,1129899.111,10002.111,518.111,20173,3.111,5.111,985.111,46,3.0,2,250261.111,1.42,0.0,2.09,29.0,86.0,3.0,1.0,0.0,89.0,15.0,8.0,Fourth Year,20151,3,65,111,0,False,False,False,0,15.0,1,0,0,0,0,0,0,1.42,0,0,0,1.42,raw_prev_gpa,0,0,1.42,2017,3,2015,1,0,4,0,0,0.046154,very_large,0.148515,3.111__518.111
209,957383.111,10003.111,657.111,20154,2.111,2.111,985.111,48,3.0,2,203890.111,2.5,0.0,1.07,7.0,17.0,19.0,5.0,0.0,17.0,23.0,4.0,Second Year,20151,3,22,111,0,False,False,False,0,23.0,1,0,0,0,0,0,0,2.5,0,0,0,2.50,raw_prev_gpa,0,0,2.50,2015,4,2015,1,0,2,0,0,0.136364,medium,0.575000,2.111__657.111
212,957382.111,10003.111,658.111,20154,2.111,2.111,985.111,43,4.0,2,203890.111,2.5,0.0,1.07,7.0,17.0,19.0,5.0,0.0,17.0,23.0,4.0,Second Year,20151,3,22,111,0,False,False,False,0,23.0,1,0,0,0,0,0,0,2.5,0,0,0,2.50,raw_prev_gpa,0,0,2.50,2015,4,2015,1,0,2,0,0,0.181818,medium,0.575000,2.111__658.111
218,957384.111,10003.111,659.111,20154,2.111,2.111,985.111,49,4.0,2,203890.111,2.5,0.0,1.07,7.0,17.0,19.0,5.0,0.0,17.0,23.0,4.0,Second Year,20151,3,22,111,0,False,False,False,0,23.0,1,0,0,0,0,0,0,2.5,0,0,0,2.50,raw_prev_gpa,0,0,2.50,2015,4,2015,1,0,2,0,0,0.181818,medium,0.575000,2.111__659.111
231,957381.111,10003.111,673.111,20154,2.111,2.111,985.111,47,4.0,2,203890.111,2.5,0.0,1.07,7.0,17.0,19.0,5.0,0.0,17.0,23.0,4.0,Second Year,20151,5,210,111,0,False,False,False,0,23.0,1,0,0,0,0,0,0,2.5,0,0,0,2.50,raw_prev_gpa,0,0,2.50,2015,4,2015,1,0,2,0,0,0.019048,very_large,0.575000,2.111__673.111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761078,1299168.111,9995.111,980.111,20192,13.111,4.111,985.111,46,2.0,2,278522.111,1.19,0.0,1.99,26.0,65.0,12.0,5.0,0.0,76.0,45.0,14.0,Third year,20151,5,129,111,0,False,False,False,0,45.0,1,0,2,0,0,0,0,1.19,0,0,0,1.19,raw_prev_gpa,0,0,1.19,2019,2,2015,1,0,3,0,0,0.015504,very_large,0.409091,13.111__980.111
761086,1299167.111,9995.111,984.111,20192,13.111,4.111,985.111,41,2.0,3,278522.111,1.19,0.0,1.99,26.0,65.0,12.0,5.0,0.0,76.0,45.0,14.0,Third year,20151,3,24,111,0,False,False,False,0,45.0,1,0,2,0,0,0,0,1.19,0,0,0,1.19,raw_prev_gpa,0,0,1.19,2019,2,2015,1,0,3,0,0,0.083333,medium,0.409091,13.111__984.111
761146,1093456.111,9997.111,309.111,20172,1.111,3.111,985.111,12,2.0,3,242408.111,1.38,0.0,1.96,20.0,50.0,17.0,6.0,0.0,50.0,27.0,6.0,Second Year,20151,3,170,111,0,False,False,False,0,27.0,1,0,0,0,0,0,0,1.38,0,0,0,1.38,raw_prev_gpa,0,0,1.38,2017,2,2015,1,0,2,0,0,0.011765,very_large,0.350649,1.111__309.111
761199,1093459.111,9997.111,359.111,20172,1.111,3.111,985.111,46,3.0,1,242408.111,1.38,0.0,1.96,20.0,50.0,17.0,6.0,0.0,50.0,27.0,6.0,Second Year,20151,3,170,111,0,False,False,False,0,27.0,1,0,0,0,0,0,0,1.38,0,0,0,1.38,raw_prev_gpa,0,0,1.38,2017,2,2015,1,0,2,0,0,0.017647,very_large,0.350649,1.111__359.111
761239,956714.111,9998.111,301.111,20154,1.111,3.111,985.111,37,3.0,3,202555.111,1.83,0.0,0.96,6.0,13.0,3.0,1.0,0.0,13.0,20.0,4.0,First Year,20151,3,170,111,0,False,False,False,0,20.0,1,0,0,0,0,0,0,1.83,0,0,0,1.83,raw_prev_gpa,0,0,1.83,2015,4,2015,1,0,1,0,0,0.017647,very_large,0.606061,1.111__301.111

In [9]:
df.head(200)

,student_course_id,student_id,course_id,part_id,degree_id,faculty_id,grade_id,final_mark,course_credits,attempt_number,student_status_id,prev_gpa_points,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,semester_reg_credits,semester_reg_courses,semester_pass_credits,total_pass_credits,total_fail_credits,reg_total_semesters,start_level_name_pl,start_part_id,requirement_type_id,degree_requirement_credits_count,university_id,is_high_credit_course,over_policy_semester_credits,over_policy_semester_courses,exclude_over_policy_semester,is_extreme_fail_history,total_fail_credits_capped,is_interruption_semester,prev_semester_was_interruption,prior_interruption_count,consecutive_interruption_count,no_previous_progress,is_first_active_semester,is_first_row_in_timeline,last_valid_gpa_before_current_semester,prev_gpa_points_missing,prev_gpa_points_zero,prev_gpa_invalid_zero_case,prev_gpa_points_clean,prev_gpa_fill_source,prev_gpa_replaced_due_to_invalid_zero,prev_gpa_actual_zero_performance,model_prev_gpa,part_year,part_semester,start_year,start_semester,start_level_missing,start_level_ord,requirement_type_missing,degree_requirement_credits_count_missing,course_share_of_requirement,requirement_size_bucket,fail_credit_ratio_capped,degree_course_key
0,939272.111,10000.111,1016.111,20152,3.111,5.111,677.111,82,2.0,1,155348.111,2.41,2.36,2.41,6.0,17.0,18.0,6.0,18.0,17.0,0.0,2.0,First Year,20151,2,6,111,0,False,False,False,0,0.0,0,0,0,0,0,0,0,2.41,0,0,0,2.41,raw_prev_gpa,0,0,2.41,2015,2,2015,1,0,1,0,0,0.333333,small,0.000000,3.111__1016.111
1,953865.111,10000.111,1017.111,20153,3.111,5.111,680.111,67,2.0,1,155349.111,2.36,2.25,2.39,12.0,35.0,9.0,3.0,9.0,35.0,0.0,3.0,Second Year,20151,2,6,111,0,False,False,False,0,0.0,0,0,0,0,0,0,0,2.36,0,0,0,2.36,raw_prev_gpa,0,0,2.36,2015,3,2015,1,0,2,0,0,0.333333,small,0.000000,3.111__1017.111
2,1076397.111,10000.111,1019.111,20171,3.111,5.111,981.111,66,2.0,1,240678.111,2.17,1.76,2.28,27.0,80.0,17.0,6.0,17.0,80.0,0.0,6.0,Third year,20151,2,6,111,0,False,False,False,0,0.0,0,0,0,0,0,0,0,2.17,0,0,0,2.17,raw_prev_gpa,0,0,2.17,2017,1,2015,1,0,3,0,0,0.333333,small,0.000000,3.111__1019.111
3,925010.111,10000.111,431.111,20152,3.111,5.111,677.111,83,3.0,1,155348.111,2.41,2.36,2.41,6.0,17.0,18.0,6.0,18.0,17.0,0.0,2.0,First Year,20151,3,65,111,0,False,False,False,0,0.0,0,0,0,0,0,0,0,2.41,0,0,0,2.41,raw_prev_gpa,0,0,2.41,2015,2,2015,1,0,1,0,0,0.046154,very_large,0.000000,3.111__431.111
4,901340.111,10000.111,432.111,20151,3.111,5.111,681.111,61,4.0,1,155347.111,<NA>,2.41,0.0,0.0,0.0,17.0,6.0,17.0,0.0,0.0,1.0,First Year,20151,3,65,111,0,False,False,False,0,0.0,0,0,0,0,1,1,1,<NA>,1,0,0,0.00,zero_fallback,0,0,NaN,2015,1,2015,1,0,1,0,0,0.061538,very_large,0.000000,3.111__432.111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1115725.111,10002.111,541.111,20172,3.111,5.111,982.111,60,3.0,1,243936.111,2.45,1.42,2.23,25.0,74.0,18.0,6.0,12.0,77.0,9.0,7.0,Third year,20151,6,21,111,0,False,False,False,0,9.0,0,0,0,0,0,0,0,2.45,0,0,0,2.45,raw_prev_gpa,0,0,2.45,2017,2,2015,1,0,3,0,0,0.142857,medium,0.108434,3.111__541.111
196,1430272.111,10002.111,542.111,20201,3.111,5.111,980.111,71,3.0,1,290533.111,2.5,2.46,2.25,52.0,152.0,18.0,6.0,18.0,155.0,26.0,15.0,Fifth year,20151,6,21,111,0,False,False,False,0,26.0,0,0,1,0,0,0,0,2.5,0,0,0,2.50,raw_prev_gpa,0,0,2.50,2020,1,2015,1,0,5,0,0,0.142857,medium,0.146067,3.111__542.111
197,1222923.111,10002.111,544.111,20183,3.111,5.111,982.111,64,3.0,1,268869.111,1.47,1.88,2.06,37.0,111.0,6.0,2.0,6.0,114.0,26.0,11.0,Fourth Year,20151,6,21,111,0,False,False,False,0,26.0,0,0,1,0,0,0,0,1.47,0,0,0,1.47,raw_prev_gpa,0,0,1.47,2018,3,2015,1,0,4,0,0,0.142857,medium,0.189781,3.111__544.111
198,1430268.111,10002.111,545.111,20201,3.111,5.111,981.111,69,3.0,1,290533.111,2.5,2.46,2.25,52.0,152.0,18.0,6.0,18.0,155.0,26.0,15.0,Fifth year,20151,6,21,111,0,False,False,False,0,26.0,0,0,1,0,0,0,0,2.5,0,0,0,2.50,raw_prev_gpa,0,0,2.50,2020,1,2015,1,0,5,0,0,0.142857,medium,0.146067,3.111__545.111
199,901392.111,10002.111,955.111,20151,3.111,5.111,985.111,47,2.0,1,203884.111,<NA>,2.29,0.0,0.0,0.0,17.0,6.0,15.0,0.0,0.0,1.0,First Year,20151,1,9,111,0,False,False,False,0,0.0,0,0,0,0,1,1,1,<NA>,1,0,0,0.00,zero_fallback,0,0,NaN,2015,1,2015,1,0,1,0,0,0.222222,small,0.000000,3.111__955.111

In [15]:
df[(df['part_id']=='20164')&(df['student_id']=='10003.111')]

,student_course_id,student_id,course_id,part_id,degree_id,faculty_id,grade_id,final_mark,course_credits,attempt_number,student_status_id,prev_gpa_points,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,semester_reg_credits,semester_reg_courses,semester_pass_credits,total_pass_credits,total_fail_credits,reg_total_semesters,start_level_name_pl,start_part_id,requirement_type_id,degree_requirement_credits_count,university_id,is_high_credit_course,over_policy_semester_credits,over_policy_semester_courses,exclude_over_policy_semester,is_extreme_fail_history,total_fail_credits_capped,is_interruption_semester,prev_semester_was_interruption,prior_interruption_count,consecutive_interruption_count,no_previous_progress,is_first_active_semester,is_first_row_in_timeline,last_valid_gpa_before_current_semester,prev_gpa_points_missing,prev_gpa_points_zero,prev_gpa_invalid_zero_case,prev_gpa_points_clean,prev_gpa_fill_source,prev_gpa_replaced_due_to_invalid_zero,prev_gpa_actual_zero_performance,model_prev_gpa,part_year,part_semester,start_year,start_semester,start_level_missing,start_level_ord,requirement_type_missing,degree_requirement_credits_count_missing,course_share_of_requirement,requirement_size_bucket,fail_credit_ratio_capped,degree_course_key
210,1048487.111,10003.111,657.111,20164,2.111,2.111,983.111,56,3.0,3,236051.111,1.13,0.76,1.29,12.0,36.0,24.0,6.0,11.0,36.0,63.0,8.0,Second Year,20151,3,22,111,0,False,False,False,0,63.0,0,0,1,0,0,0,0,1.13,0,0,0,1.13,raw_prev_gpa,0,0,1.13,2016,4,2015,1,0,2,0,0,0.136364,medium,0.636364,2.111__657.111
214,1040685.111,10003.111,658.111,20164,2.111,2.111,985.111,43,4.0,4,236051.111,1.13,0.76,1.29,12.0,36.0,24.0,6.0,11.0,36.0,63.0,8.0,Second Year,20151,3,22,111,0,False,False,False,0,63.0,0,0,1,0,0,0,0,1.13,0,0,0,1.13,raw_prev_gpa,0,0,1.13,2016,4,2015,1,0,2,0,0,0.181818,medium,0.636364,2.111__658.111
235,1040687.111,10003.111,675.111,20164,2.111,2.111,983.111,56,4.0,2,236051.111,1.13,0.76,1.29,12.0,36.0,24.0,6.0,11.0,36.0,63.0,8.0,Second Year,20151,5,210,111,0,False,False,False,0,63.0,0,0,1,0,0,0,0,1.13,0,0,0,1.13,raw_prev_gpa,0,0,1.13,2016,4,2015,1,0,2,0,0,0.019048,very_large,0.636364,2.111__675.111
245,1043292.111,10003.111,680.111,20164,2.111,2.111,985.111,43,5.0,2,236051.111,1.13,0.76,1.29,12.0,36.0,24.0,6.0,11.0,36.0,63.0,8.0,Second Year,20151,5,210,111,0,False,False,False,0,63.0,0,0,1,0,0,0,0,1.13,0,0,0,1.13,raw_prev_gpa,0,0,1.13,2016,4,2015,1,0,2,0,0,0.023810,very_large,0.636364,2.111__680.111
253,1040682.111,10003.111,684.111,20164,2.111,2.111,984.111,53,4.0,2,236051.111,1.13,0.76,1.29,12.0,36.0,24.0,6.0,11.0,36.0,63.0,8.0,Second Year,20151,5,210,111,0,False,False,False,0,63.0,0,0,1,0,0,0,0,1.13,0,0,0,1.13,raw_prev_gpa,0,0,1.13,2016,4,2015,1,0,2,0,0,0.019048,very_large,0.636364,2.111__684.111
256,1043291.111,10003.111,685.111,20164,2.111,2.111,985.111,35,4.0,2,236051.111,1.13,0.76,1.29,12.0,36.0,24.0,6.0,11.0,36.0,63.0,8.0,Second Year,20151,5,210,111,0,False,False,False,0,63.0,0,0,1,0,0,0,0,1.13,0,0,0,1.13,raw_prev_gpa,0,0,1.13,2016,4,2015,1,0,2,0,0,0.019048,very_large,0.636364,2.111__685.111