In [ ]:
import pandas as pd 
df=pd.read_csv(r'D:/AI/Real projects/Academic_Advisor/models/runs/COURSE_IDENTITY_67_HUMAN_REVIEW.csv')

In [2]:
df.head(10)

,new_course_id,new_course_name,new_degree_id,old_course_id,old_course_name,old_degree_id,same_degree,credits_old_new,course_type_old_new,requirement_type_old_new,planned_year_old_new,last_old_semester,first_new_semester,enrolment_overlap,new_valid_row_count,diagnostic_conclusion,review_decision,reviewer_name,review_date,review_notes
0,1423.111,اللغة الإنكليزية – 1,40.111|41.111|42.111|44.111|45.111|46.111|47.1...,391.111,اللغة الإنكليزية 1,18.111,False,3 → 3,3 → 1,1 → 1,1 → 1,20142,20231,False,979,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
1,1175.111,التحليل الرياضي1,26.111|27.111|29.111|30.111|31.111|45.111|46.1...,502.111,التحليل الرياضي 1,21.111|3.111|4.111|5.111|6.111,False,4 → 3,3 → 3,3 → 3,1 → 1,20232,20221,True,917,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
2,1172.111,الرياضيات المتقطعة,26.111|27.111|29.111|30.111|31.111|45.111|46.1...,431.111,الرياضيات المتقطعة,21.111|3.111|4.111|5.111|6.111,False,3 → 3,1 → 3,3 → 3,1 → 1,20232,20221,True,876,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
3,1174.111,الفيزياء1,26.111|27.111|29.111|30.111|31.111|45.111|46.1...,501.111,الفيزياء 1,21.111|3.111|4.111|5.111|6.111,False,3 → 3,3 → 3,3 → 3,1 → 1,20232,20221,True,791,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
4,1179.111,الفيزياء2,26.111|27.111|29.111|30.111|31.111|45.111|46.1...,457.111,الفيزياء 2,5.111|6.111,False,3 → 3,3 → 3,5 → 3,1 → 1,20222,20222,True,759,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
5,1173.111,الجبر الخطي ونظرية المصفوفات,26.111|27.111|29.111|30.111|31.111|45.111|46.1...,432.111,الجبر الخطي ونظرية المصفوفات,21.111|3.111|4.111|5.111|6.111,False,4 → 3,3 → 3,3 → 3,1 → 1,20232,20221,True,719,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
6,1422.111,مهارات الحاسوب,40.111|41.111|42.111|44.111|45.111|46.111|47.1...,967.111,مهارات الحاسوب,1.111|10.111|11.111|12.111|13.111|2.111|21.111...,False,3 → 3,3 → 3,1 → 1,1|2 → 1|2|3,20233,20231,True,686,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
7,1365.111,رياضيات الأعمال,33.111|34.111|35.111|36.111|37.111|38.111|39.1...,118.111,رياضيات الأعمال,10.111|11.111|12.111|22.111|7.111|8.111|9.111,False,3 → 3,3 → 3,3 → 3,1 → 1,20233,20221,True,638,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
8,1332.111,إدارة الموارد البشرية,33.111|34.111|35.111|36.111|37.111|38.111|39.1...,73.111,إدارة الموارد البشرية,10.111|11.111|12.111|22.111|7.111|8.111|9.111,False,3 → 3,1 → 1,3 → 3,2 → 1,20233,20221,True,594,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN
9,1372.111,مبادئ الإدارة,33.111|34.111|35.111|36.111|37.111|38.111|39.1...,70.111,مبادئ الإدارة,10.111|11.111|12.111|22.111|7.111|8.111|9.111,False,2 → 3,1 → 1,3 → 3,1 → 1,20233,20221,True,579,SAME_UNIVERSITY_DIFFERENT_DEGREE,NaN,NaN,NaN,NaN

In [3]:
df1=pd.read_parquet(r'D:\AI\Real projects\Academic_Advisor\data\raw\v_acd_degree_course.parquet')

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4006 entries, 0 to 4005
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   degree_course_id     4006 non-null   float64
 1   course_id            4006 non-null   float64
 2   degree_id            4006 non-null   float64
 3   faculty_id           1526 non-null   float64
 4   course_type_id       4006 non-null   float64
 5   requirement_type_id  4006 non-null   float64
 6   requirement_type_sl  4006 non-null   str
 7   course_name_sl       4006 non-null   str
 8   course_official_sl   4006 non-null   str
 9   degree_name_sl       4006 non-null   str
 10  year_order           3997 non-null   float64
 11  semester_order       3997 non-null   float64
 12  required_credits     296 non-null    float64
 13  course_credits       4006 non-null   float64
 14  active               4006 non-null   str
 15  credits_count        4006 non-null   float64
 16  req_degree_id        1599 non-null   float64
dtypes: float64(12), str(5)
memory usage: 1.2 MB

In [8]:
df1

,degree_course_id,course_id,degree_id,faculty_id,course_type_id,requirement_type_id,requirement_type_sl,course_name_sl,course_official_sl,degree_name_sl,year_order,semester_order,required_credits,course_credits,active,credits_count,req_degree_id
0,1.111,917.111,17.111,NaN,3.0,5.0,متطلبات الشهادة الإجبارية,الكيمياء الحيوية,الكيمياء الحيوية,الصيدلة,3.0,1.0,NaN,4.0,A,193.0,17.111
1,2.111,923.111,17.111,NaN,3.0,5.0,متطلبات الشهادة الإجبارية,الكيمياء الحيوية التطبيقية,الكيمياء الحيوية التطبيقية,الصيدلة,3.0,2.0,NaN,3.0,A,193.0,17.111
2,3.111,908.111,17.111,NaN,1.0,5.0,متطلبات الشهادة الإجبارية,الإحصاء الحيوي,الإحصاء الحيوي,الصيدلة,2.0,1.0,NaN,2.0,A,193.0,17.111
3,4.111,891.111,17.111,NaN,3.0,5.0,متطلبات الشهادة الإجبارية,البيولوجيا النباتية,البيولوجيا النباتية,الصيدلة,1.0,1.0,NaN,4.0,A,193.0,17.111
4,5.111,907.111,17.111,NaN,1.0,5.0,متطلبات الشهادة الإجبارية,تجارة الأدوية,تجارة الأدوية,الصيدلة,2.0,1.0,NaN,2.0,A,193.0,17.111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4001,4135.111,1664.111,65.111,195.111,3.0,3.0,متطلبات الكلية الإجبارية,اقتصاديات البناء والتشييد,اقتصاديات البناء والتشييد,هندسة تكنولوجيا البناء والتشييد,5.0,2.0,140.0,3.0,A,165.0,NaN
4002,4136.111,1665.111,65.111,195.111,1.0,3.0,متطلبات الكلية الإجبارية,إدارة الجودة في التشييد والبناء,إدارة الجودة في التشييد والبناء,هندسة تكنولوجيا البناء والتشييد,5.0,2.0,NaN,2.0,A,165.0,NaN
4003,4137.111,1666.111,65.111,195.111,1.0,3.0,متطلبات الكلية الإجبارية,آداب واخلاقيات العمل الهندسي,آداب واخلاقيات العمل الهندسي,هندسة تكنولوجيا البناء والتشييد,5.0,2.0,140.0,2.0,A,165.0,NaN
4004,4138.111,1667.111,65.111,195.111,2.0,3.0,متطلبات الكلية الإجبارية,التدريب العملي الميداني,التدريب العملي الميداني,هندسة تكنولوجيا البناء والتشييد,5.0,2.0,140.0,3.0,A,165.0,NaN
4005,4139.111,1668.111,65.111,195.111,3.0,3.0,متطلبات الكلية الإجبارية,مشروع التخرج 2,مشروع التخرج 2,هندسة تكنولوجيا البناء والتشييد,5.0,2.0,NaN,5.0,A,165.0,NaN

In [10]:
df1['degree_id'].nunique()

58

In [11]:
df1['course_id'].nunique()

1503

In [2]:
c=pd.read_csv(r'D:\AI\Real projects\Academic_Advisor\models\runs\phase2_train_membership_revision\course_split_candidates.csv')