In [9]:
import pandas as pd

In [16]:
df=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_acd_degree_course.parquet")
df.tail(10)

,degree_course_id,course_id,course_name_sl,degree_id,degree_name_sl,year_order,semester_order,course_credits,active,credits_count,faculty_id,required_level,requirement_type_sl,req_degree_id
1690,1608.101,476.111,تجهيزات وتمديدات المباني,4.111,هندسة الذكاء الصنعي,NaN,NaN,3.0,A,21.0,NaN,NaN,متطلبات الشهادة الاختيارية,4.111
1691,1609.101,544.111,برمجة التطبيقات الشبكية,4.111,هندسة الذكاء الصنعي,NaN,NaN,3.0,A,21.0,NaN,NaN,متطلبات الشهادة الاختيارية,4.111
1692,1610.101,545.111,نظم المعلومات الإدارية,4.111,هندسة الذكاء الصنعي,NaN,NaN,3.0,A,21.0,NaN,NaN,متطلبات الشهادة الاختيارية,4.111
1693,1611.101,540.111,تطبيقات إنترنت,4.111,هندسة الذكاء الصنعي,NaN,NaN,3.0,A,21.0,NaN,4.0,متطلبات الشهادة الاختيارية,4.111
1694,1612.101,542.111,أمن الشبكات,4.111,هندسة الذكاء الصنعي,NaN,NaN,3.0,A,21.0,NaN,NaN,متطلبات الشهادة الاختيارية,4.111
1695,1613.101,1095.000,NaN,3.111,هندسة البرمجيات ونظم المعلومات,1.0,1.0,NaN,A,9.0,NaN,NaN,متطلبات الجامعة الإجبارية,NaN
1696,1614.101,1096.000,NaN,3.111,هندسة البرمجيات ونظم المعلومات,1.0,1.0,NaN,A,9.0,NaN,NaN,متطلبات الجامعة الإجبارية,NaN
1697,1615.101,1097.000,NaN,3.111,هندسة البرمجيات ونظم المعلومات,1.0,1.0,NaN,A,9.0,NaN,NaN,متطلبات الجامعة الإجبارية,NaN
1698,1616.101,1163.101,NaN,3.111,هندسة البرمجيات ونظم المعلومات,1.0,1.0,NaN,A,63.0,NaN,NaN,متطلبات الشهادة الإجبارية,3.111
1699,1617.101,1164.101,NaN,3.111,هندسة البرمجيات ونظم المعلومات,2.0,1.0,NaN,A,63.0,NaN,NaN,متطلبات الشهادة الإجبارية,3.111

In [14]:
df1=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_acs_grade.parquet")
df1.head(5)

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
0,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
1,673.111,2.111,القرار الوزاري الموحد,2,98.0,100.0,4.00,20111.0,20162.0,P,A+,A
2,999.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.00,20051.0,20111.0,NaN,NaN,A
3,974.111,3.111,القرار رقم 230,230,98.0,100.0,4.00,20162.0,NaN,P,A+,A
4,674.111,2.111,القرار الوزاري الموحد,2,95.0,97.0,3.75,20111.0,20162.0,P,A,A

In [15]:
df1.tail(10)

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
98,1006.111,2.111,القرار الوزاري الموحد,2,0.0,0.0,0.0,20111.0,20162.0,X,X,A
99,1006.111,2.111,القرار الوزاري الموحد,2,0.0,0.0,0.0,20111.0,20162.0,X,X,A
100,1005.111,3.111,القرار رقم 230,230,0.0,0.0,0.0,20162.0,NaN,L,L,A
101,1007.111,2.111,القرار الوزاري الموحد,2,0.0,0.0,0.0,20111.0,20162.0,L,L,A
102,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
103,1009.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.0,20051.0,20111.0,L,L,A
104,NaN,1.111,تأسيس الجامعة,1,NaN,NaN,NaN,20051.0,20111.0,NaN,NaN,A
105,NaN,2.111,القرار الوزاري الموحد,2,NaN,NaN,NaN,20111.0,20162.0,NaN,NaN,A
106,NaN,3.111,القرار رقم 230,230,NaN,NaN,NaN,20162.0,NaN,NaN,NaN,A
107,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A

In [18]:
l=df1.columns
len(l)

12

In [19]:
df2=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_add_student_degree_status.parquet")

In [24]:

print(df2.columns)

Index(['student_id', 'request_id', 'part_id', 'degree_id', 'study_mode',
       'gpa_percent', 'gpa_points', 'end_agpa_percent', 'end_agpa_points',
       'semester_reg_courses', 'semester_reg_credits', 'semester_pass_courses',
       'semester_pass_credits', 'semester_fail_courses',
       'semester_fail_credits', 'total_pass_courses', 'total_pass_credits',
       'total_fail_courses', 'total_fail_credits', 'reg_total_semesters',
       'finish_status', 'version_title_sl', 'start_level_id',
       'start_level_name_pl'],
      dtype='str')

In [22]:
df2.tail()

,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,...,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
154774,16037.111,767462.111,20242.0,10.111,C,0.0,0.0,70.26,2.43,4.0,...,0.0,43.0,112.0,10.0,25.0,12.0,NaN,القرار رقم 230,713.111,Fourth Year
154775,16037.111,837273.111,20251.0,10.111,C,0.0,0.0,70.26,2.43,0.0,...,0.0,43.0,112.0,10.0,25.0,12.0,NaN,القرار رقم 230,713.111,Fourth Year
154776,16038.111,254725.111,20201.0,NaN,C,0.0,0.0,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
154777,16039.111,254726.111,20201.0,NaN,C,0.0,0.0,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
154778,16040.111,291021.111,20201.0,1.111,C,0.0,0.0,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,CANCEL_ADMISSION,القرار رقم 230,595.111,First Year