In [ ]:
import pandas as pd 
import numpy as np

In [2]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)
pd.set_option("display.max_colwidth", 120)

In [6]:
df_crg=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_CRG_STUDENT_COURSE\clean_v_crg_student_course.parquet")
df_add=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_ADD_STUDENT_DEGREE_STATUS\clean_v_add_student_degree_status.parquet")
df_acd=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_ACD_DEGREE_COURSE\v_acd_degree_course.parquet")
df_acs=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_ACS_GRADE\clean_v_acs_grade.parquet")

In [13]:
df_acd.shape

(4006, 12)

In [17]:
df_acd.info()

<class 'pandas.DataFrame'>
RangeIndex: 4006 entries, 0 to 4005
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   degree_course_id      4006 non-null   float64
 1   course_id             4006 non-null   float64
 2   degree_id             4006 non-null   float64
 3   requirement_type_id   4006 non-null   Int64
 4   requirement_type_sl   4006 non-null   str
 5   course_name_sl        4006 non-null   str
 6   degree_name_sl        4006 non-null   str
 7   course_credits        4006 non-null   float64
 8   credits_count         4006 non-null   Int64
 9   degree_course_id_key  4006 non-null   string
 10  course_id_key         4006 non-null   string
 11  degree_id_key         4006 non-null   string
dtypes: Int64(2), float64(4), str(3), string(3)
memory usage: 1005.3 KB

In [8]:
df_acd.head(2)

,degree_course_id,course_id,degree_id,requirement_type_id,requirement_type_sl,course_name_sl,degree_name_sl,course_credits,credits_count,degree_course_id_key,course_id_key,degree_id_key
0,1.111,917.111,17.111,5,متطلبات الشهادة الإجبارية,الكيمياء الحيوية,الصيدلة,4.0,193,1.111,917.111,17.111
1,2.111,923.111,17.111,5,متطلبات الشهادة الإجبارية,الكيمياء الحيوية التطبيقية,الصيدلة,3.0,193,2.111,923.111,17.111

In [14]:
df_acs.shape

(40, 12)

In [9]:
df_acs.head(2)

,grade_id,grade_id_key,grade_version_id,grade_version_id_key,version_number,version_title_sl,from_percent,to_percent,points,finish_status,grade_show,grade_name_sl
0,1003.111,1003.111,1.111,1.111,1,تأسيس الجامعة,0,0,0.0,FE,F,راسب امتحان نهائي
1,96.111,96.111,1.111,1.111,1,تأسيس الجامعة,0,0,0.0,FA,Z,محروم بالغياب

In [15]:
df_crg.shape

(761347, 21)

In [10]:
df_crg.head(2)

,student_course_id,student_id,course_id,part_id,degree_id,faculty_id,grade_id,final_mark,points,finish_status,course_outcome_status,register_status,in_credits,in_gpa,in_agpa,study_mode,course_credits,course_name_sl,degree_name_sl,attempt_number,attempt_count
0,939272.111,10000.111,1016.111,20152,3.111,5.111,677.111,82,3.0,P,passed,R,Y,Y,Y,C,2.0,المنطق والتفكير العلمي,هندسة البرمجيات ونظم المعلومات,1,1
1,953865.111,10000.111,1017.111,20153,3.111,5.111,680.111,67,2.25,P,passed,R,Y,Y,Y,C,2.0,لغة اجنبية حية (ثانية),هندسة البرمجيات ونظم المعلومات,1,1

In [16]:
df_add.shape

(179844, 41)

In [11]:
df_add.head(2)

,student_status_id,student_id,part_id,degree_id,start_part_id,finish_part_id,grade_version_id,prev_gpa_points,prev_gpa_percent,gpa_points,gpa_percent,start_agpa_points,start_agpa_percent,end_agpa_points,end_agpa_percent,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,semester_in_courses,semester_in_credits,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,total_semesters,reg_total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,finish_status,version_title_sl,degree_name_sl,degree_credits_count,start_level_id,start_level_name_pl
0,297550.111,48.111,20203,22.111,20203,20212,3.111,0.0,0.0,0.0,0.0,0.97,39.4,0.93,38.6,2.0,4.0,0.0,0.0,2.0,4.0,0.0,0.0,26.0,66.0,26.0,66.0,16.0,12.0,73.0,180.0,26.0,66.0,47.0,114.0,CLOSE_FILE,القرار رقم 230,إدارة (اختصاص عام),72.0,692.111,Third year
1,314343.111,48.111,20211,22.111,20203,20212,3.111,0.0,0.0,0.0,0.0,0.93,38.6,0.93,38.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,66.0,26.0,66.0,17.0,12.0,75.0,184.0,26.0,66.0,49.0,118.0,CLOSE_FILE,القرار رقم 230,إدارة (اختصاص عام),72.0,692.111,Third year

SyntaxError: invalid syntax (1698658035.py, line 1)