## setup and connect with data base

In [1]:
import oracledb 
import pandas as pd

from src.paths import RAW_DIR
from src.db_connect import get_connection


connection = get_connection()

In [2]:
cursor = connection.cursor()
cursor.arraysize = 10_000
pd.set_option('display.max_columns', None)

In [3]:
print("RAW_DIR:", RAW_DIR)

RAW_DIR: D:\AI\Real projects\Academic_Advisor\data\raw

In [7]:
VIEW_NAME = "RAS_USER.V_CRG_STUDENT_COURSE"

needed_columns = [
    "STUDENT_COURSE_ID",
    "STUDENT_ID",
    "COURSE_ID",
    "PART_ID",
    "GRADE_ID",
    "FINAL_MARK",
    "POINTS",
    "FINISH_STATUS",
    "COURSE_NAME_SL",
    "REGISTER_STATUS",
    "STUDY_MODE",
    "DEGREE_ID",
    "DEGREE_NAME_SL",
    "FACULTY_ID",
    "COURSE_CREDITS",
    "ACTIVE",
]

query = f"""
SELECT
    STUDENT_COURSE_ID,
    STUDENT_ID,
    COURSE_ID,
    PART_ID,
    GRADE_ID,
    FINAL_MARK,
    POINTS,
    FINISH_STATUS,
    COURSE_NAME_SL,
    REGISTER_STATUS,
    IN_CREDITS,
    IN_GPA,
    IN_AGPA,
    STUDY_MODE,
    DEGREE_ID,
    STUDENT_NAME_SL,
    DEGREE_NAME_SL,
    FACULTY_ID,
    COURSE_CREDITS,
    ACTIVE
FROM {VIEW_NAME}
WHERE ACTIVE = 'A'
  AND STUDY_MODE = 'C'
"""

df_v_crg_student_course = pd.read_sql(query, connection)
df_v_crg_student_course.columns = df_v_crg_student_course.columns.str.lower()

df_v_crg_student_course.to_parquet(RAW_DIR / "v_crg_student_course_raw.parquet",index=False)

print("Rows loaded:", len(df_v_crg_student_course))
print("Columns:", df_v_crg_student_course.columns.tolist())
print("Saved:", RAW_DIR / "v_crg_student_course_raw.parquet")
display(df_v_crg_student_course.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23720\2135910440.py:49: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_crg_student_course = pd.read_sql(query, connection)

Rows loaded: 1004459
Columns: ['student_course_id', 'student_id', 'course_id', 'part_id', 'grade_id', 'final_mark', 'points', 'finish_status', 'course_name_sl', 'register_status', 'in_credits', 'in_gpa', 'in_agpa', 'study_mode', 'degree_id', 'student_name_sl', 'degree_name_sl', 'faculty_id', 'course_credits', 'active']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_crg_student_course_raw.parquet

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,finish_status,course_name_sl,register_status,in_credits,in_gpa,in_agpa,study_mode,degree_id,student_name_sl,degree_name_sl,faculty_id,course_credits,active
0,430311.111,2117.111,962.111,20132.0,679.111,70.0,2.50,P,اللغة الانكليزية 2,R,Y,Y,Y,C,13.111,محمد نبيل حلواني,الصيدلة و الكيمياء الصيدلية,4.111,2.0,A
1,430312.111,2117.111,966.111,20132.0,680.111,68.0,2.25,P,كيمياء عضوية صيدلانية 1,R,Y,Y,Y,C,13.111,محمد نبيل حلواني,الصيدلة و الكيمياء الصيدلية,4.111,3.0,A
2,430313.111,2117.111,967.111,20132.0,680.111,69.0,2.25,P,مهارات الحاسوب,R,Y,Y,Y,C,13.111,محمد نبيل حلواني,الصيدلة و الكيمياء الصيدلية,4.111,3.0,A
3,430314.111,2117.111,963.111,20132.0,684.111,48.0,0.00,F,بيولوجيا نباتية,R,Y,Y,Y,C,13.111,محمد نبيل حلواني,الصيدلة و الكيمياء الصيدلية,4.111,3.0,A
4,430315.111,2117.111,964.111,20132.0,679.111,70.0,2.50,P,إحصاء حيوي,R,Y,Y,Y,C,13.111,محمد نبيل حلواني,الصيدلة و الكيمياء الصيدلية,4.111,2.0,A

In [6]:
VIEW_NAME = "RAS_USER.V_ACS_GRADE"

needed_columns = [
    "GRADE_ID",
    "GRADE_VERSION_ID",
    "VERSION_TITLE_SL",
    "VERSION_NUMBER",
    "FROM_PERCENT",
    "TO_PERCENT",
    "POINTS",
    "FINISH_STATUS",
    "GRADE_SHOW",
    "FROM_SEMESTER_ID",
    "TILL_SEMESTER_ID",
    "ACTIVE",
]

query = f"""
SELECT
    GRADE_ID,
    GRADE_VERSION_ID,
    GRADE_NAME_SL,
    VERSION_TITLE_SL,
    VERSION_NUMBER,
    FROM_PERCENT,
    TO_PERCENT,
    POINTS,
    FINISH_STATUS,
    GRADE_SHOW,
    ACTIVE
FROM {VIEW_NAME}
WHERE ACTIVE = 'A'
"""

df_v_acs_grade = pd.read_sql(query, connection)
df_v_acs_grade.columns = df_v_acs_grade.columns.str.lower()

df_v_acs_grade.to_parquet(RAW_DIR / "v_acs_grade.parquet",index=False)

print("Rows loaded:", len(df_v_acs_grade))
print("Columns:", df_v_acs_grade.columns.tolist())
print("Saved:", RAW_DIR / "v_acs_grade.parquet")

display(df_v_acs_grade.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23720\312241839.py:35: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_acs_grade = pd.read_sql(query, connection)

Rows loaded: 72
Columns: ['grade_id', 'grade_version_id', 'grade_name_sl', 'version_title_sl', 'version_number', 'from_percent', 'to_percent', 'points', 'finish_status', 'grade_show', 'active']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_acs_grade.parquet

,grade_id,grade_version_id,grade_name_sl,version_title_sl,version_number,from_percent,to_percent,points,finish_status,grade_show,active
0,673.111,2.111,شرف,القرار الوزاري الموحد,2,98,100,4.00,P,A+,A
1,999.111,1.111,NaN,تأسيس الجامعة,1,0,0,0.00,NaN,NaN,A
2,974.111,3.111,شرف,القرار رقم 230,230,98,100,4.00,P,A+,A
3,975.111,3.111,شرف,القرار رقم 230,230,95,97,3.75,P,A,A
4,85.111,1.111,ممتاز,تأسيس الجامعة,1,90,100,4.00,P,A,A

In [ ]:
VIEW_NAME = "RAS_USER.V_ADD_STUDENT_DEGREE_STATUS"

needed_columns = [
    "STUDENT_ID",
    "PART_ID",
    "DEGREE_ID",
    "STUDY_MODE",
    "GPA_PERCENT",
    "GPA_POINTS",
    "START_AGPA_PERCENT",
    "START_AGPA_POINTS",
    "END_AGPA_PERCENT",
    "END_AGPA_POINTS",
    "SEMESTER_REG_COURSES",
    "SEMESTER_REG_CREDITS",
    "SEMESTER_PASS_COURSES",
    "SEMESTER_PASS_CREDITS",
    "SEMESTER_FAIL_COURSES",
    "SEMESTER_FAIL_CREDITS",
    "TOTAL_PASS_COURSES",
    "TOTAL_PASS_CREDITS",
    "TOTAL_FAIL_COURSES",
    "TOTAL_FAIL_CREDITS",
    "REG_TOTAL_SEMESTERS",
    "FINISH_STATUS",
    "VERSION_TITLE_SL",
    "START_LEVEL_ID",
    "START_LEVEL_NAME_PL",
]

query = f"""
SELECT
    STUDENT_STATUS_ID,
    STUDENT_ID,
    PART_ID,
    DEGREE_ID,
    STUDY_MODE,
    GPA_PERCENT,
    GPA_POINTS,
    START_PART_ID,
    FINISH_PART_ID,
    START_AGPA_PERCENT,
    START_AGPA_POINTS,
    END_AGPA_PERCENT,
    END_AGPA_POINTS,
    SEMESTER_REG_COURSES,
    SEMESTER_REG_CREDITS,
    SEMESTER_PASS_COURSES,  
    SEMESTER_PASS_CREDITS,
    SEMESTER_FAIL_COURSES,
    SEMESTER_FAIL_CREDITS,
    TOTAL_PASS_COURSES,
    TOTAL_PASS_CREDITS,
    
    TOTAL_FAIL_COURSES,
    TOTAL_FAIL_CREDITS,
    REG_TOTAL_SEMESTERS,
    FINISH_STATUS,
    VERSION_TITLE_SL,
    START_LEVEL_ID,
    START_LEVEL_NAME_PL
FROM {VIEW_NAME}
WHERE STUDY_MODE = 'C'
AND ACTIVE = 'A'
"""

df_v_add_student_degree_status = pd.read_sql(query, connection)
df_v_add_student_degree_status.columns = df_v_add_student_degree_status.columns.str.lower()

df_v_add_student_degree_status.to_parquet(RAW_DIR / "v_add_student_degree_status.parquet",index=False)

print("Rows loaded:", len(df_v_add_student_degree_status))
print("Columns:", df_v_add_student_degree_status.columns.tolist())
print("Saved:", RAW_DIR / "v_add_student_degree_status.parquet")

display(df_v_add_student_degree_status.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_3904\4200191655.py:66: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_add_student_degree_status = pd.read_sql(query, connection)

KeyboardInterrupt:

In [ ]:
VIEW_NAME = "RAS_USER.V_ACD_DEGREE_COURSE"

needed_columns = [
    "DEGREE_COURSE_ID",
    "COURSE_ID",
    "COURSE_NAME_SL",
    "DEGREE_ID",
    "DEGREE_NAME_SL",
    "YEAR_ORDER",
    "SEMESTER_ORDER",
    "COURSE_CREDITS",
    "ACTIVE",
    "CREDITS_COUNT",
    "FACULTY_ID",
    "REQUIRED_CREDITS",
    "REQUIREMENT_TYPE_ID",
    "REQUIREMENT_TYPE_SL",
    "REQ_DEGREE_ID",
]

query = f"""
SELECT
    DEGREE_COURSE_ID,
    COURSE_ID,
    COURSE_NAME_SL,
    DEGREE_ID,
    DEGREE_NAME_SL,
    YEAR_ORDER,
    SEMESTER_ORDER,
    REQUIRED_CREDITS,
    COURSE_CREDITS,
    ACTIVE,
    CREDITS_COUNT,
    FACULTY_ID,
    REQUIREMENT_TYPE_ID,
    REQUIREMENT_TYPE_SL,
    REQ_DEGREE_ID
FROM {VIEW_NAME}
WHERE ACTIVE = 'A'
"""

df_v_acd_degree_course = pd.read_sql(query, connection)
df_v_acd_degree_course.columns = df_v_acd_degree_course.columns.str.lower()

df_v_acd_degree_course.to_parquet(RAW_DIR / "v_acd_degree_course.parquet",index=False)

print("Rows loaded:", len(df_v_acd_degree_course))
print("Columns:", df_v_acd_degree_course.columns.tolist())
print("Saved:", RAW_DIR / "v_acd_degree_course.parquet")

display(df_v_acd_degree_course.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24116\1767842285.py:42: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_acd_degree_course = pd.read_sql(query, connection)

Rows loaded: 1700
Columns: ['degree_course_id', 'course_id', 'course_name_sl', 'degree_id', 'degree_name_sl', 'year_order', 'semester_order', 'required_credits', 'course_credits', 'active', 'credits_count', 'faculty_id', 'requirement_type_id', 'requirement_type_sl', 'req_degree_id']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_acd_degree_course.parquet

,degree_course_id,course_id,course_name_sl,degree_id,degree_name_sl,year_order,semester_order,required_credits,course_credits,active,credits_count,faculty_id,requirement_type_id,requirement_type_sl,req_degree_id
0,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN
1,1.111,917.111,الكيمياء الحيوية,17.111,الصيدلة,3.0,1.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
2,2.111,923.111,الكيمياء الحيوية التطبيقية,17.111,الصيدلة,3.0,2.0,NaN,3.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
3,3.111,908.111,الإحصاء الحيوي,17.111,الصيدلة,2.0,1.0,NaN,2.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111
4,4.111,891.111,البيولوجيا النباتية,17.111,الصيدلة,1.0,1.0,NaN,4.0,A,193.0,NaN,5.0,متطلبات الشهادة الإجبارية,17.111

In [ ]:
VIEW_NAME = "RAS_USER.V_CRG_STUDENT_PASSED_CREDIT"

needed_columns = [
    "STUDENT_ID",
    "REQUIREMENT_TYPE_PL",
    "REQUIREMENT_TYPE_SL",
    "CREDITS_COUNT",
    "PASSED_CREDIT",
]

query = f"""
SELECT
    STUDENT_ID,
    REQUIREMENT_TYPE_PL,
    REQUIREMENT_TYPE_SL,
    CREDITS_COUNT,
    PASSED_CREDIT
FROM {VIEW_NAME}
"""

df_v_crg_student_passed_credit = pd.read_sql(query, connection)
df_v_crg_student_passed_credit.columns = df_v_crg_student_passed_credit.columns.str.lower()

df_v_crg_student_passed_credit.to_parquet(RAW_DIR / "v_crg_student_passed_credit.parquet",index=False)

print("Rows loaded:", len(df_v_crg_student_passed_credit))
print("Columns:", df_v_crg_student_passed_credit.columns.tolist())
print("Saved:", RAW_DIR / "v_crg_student_passed_credit.parquet")

display(df_v_crg_student_passed_credit.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24116\1320494628.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_crg_student_passed_credit = pd.read_sql(query, connection)

Rows loaded: 53877
Columns: ['student_id', 'requirement_type_pl', 'requirement_type_sl', 'credits_count', 'passed_credit']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_crg_student_passed_credit.parquet

,student_id,requirement_type_pl,requirement_type_sl,credits_count,passed_credit
0,2701.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,179.0
1,2722.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,196.0
2,2738.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,196.0
3,2739.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,189.0
4,2742.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,182.0

In [ ]:
VIEW_NAME = "RAS_USER.V_SCH_COURSE_OFFER"

needed_columns = [
    "COURSE_ID",
    "COURSE_CREDITS",
    "PART_ID",
    "DEPARTMENT_ID",
    "FACULTY_ID",
    "ALLOW_REGISTER",
]

query = f"""
SELECT
    COURSE_ID,
    COURSE_CREDITS,
    PART_ID,
    DEPARTMENT_ID,
    FACULTY_ID,
    ALLOW_REGISTER
FROM {VIEW_NAME}
"""

df_v_sch_course_offers = pd.read_sql(query, connection)
df_v_sch_course_offers.columns = df_v_sch_course_offers.columns.str.lower()

df_v_sch_course_offers.to_parquet(RAW_DIR / "v_sch_course_offers.parquet",index=False)

print("Rows loaded:", len(df_v_sch_course_offers))
print("Columns:", df_v_sch_course_offers.columns.tolist())
print("Saved:", RAW_DIR / "v_sch_course_offers.parquet")

display(df_v_sch_course_offers.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24116\2949394349.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_sch_course_offers = pd.read_sql(query, connection)

Rows loaded: 137899
Columns: ['course_id', 'course_credits', 'part_id', 'department_id', 'faculty_id', 'allow_register']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_sch_course_offers.parquet

,course_id,course_credits,part_id,department_id,faculty_id,allow_register
0,88.111,3.0,20050.0,37.111,7.111,NaN
1,88.111,3.0,20051.0,37.111,7.111,NaN
2,88.111,3.0,20052.0,37.111,7.111,NaN
3,88.111,3.0,20053.0,37.111,7.111,NaN
4,88.111,3.0,20060.0,37.111,7.111,NaN

In [ ]:
VIEW_NAME = "RAS_USER.V_CRG_STD_COR_TEMP_REQUEST"

needed_columns = [
"ACTIVE",
"REQUIREMENT_TYPE_ID",
"IS_REQUESTABLE",
"PASSED_PREREQUISITES",
"LAST_REGISTER_SEMESTER"
"STATUS_REASON_SL",
"STATUS_REASON_CODE",
"FINAL_MARK",
"SEMESTER_ORDER",
"YEAR_ORDER",
"COURSE_CREITS",
"COURSE_NAME_SL", 
"COURSE_ID",
"CREDITS_COUNT",
"CREDITS_TILL_GRAD",
"STUDENT_ID",
"STD_COR_TEMP_REQUEST_ID"
]

query = f"""
SELECT
ACTIVE,
REQUIREMENT_TYPE_ID,
IS_REQUESTABLE,
PASSED_PREREQUISITES,
STATUS_REASON_SL,
STATUS_REASON_CODE,
FINAL_MARK,
SEMESTER_ORDER,
YEAR_ORDER,
COURSE_CREDITS,
COURSE_NAME_SL, 
COURSE_ID,
CREDITS_COUNT,
CREDITS_TILL_GRAD,
STUDENT_ID,
STD_COR_TEMP_REQUEST_ID
FROM {VIEW_NAME}
"""

df_vcrg_std_cor_temp_request = pd.read_sql(query, connection)
df_vcrg_std_cor_temp_request.columns = df_vcrg_std_cor_temp_request.columns.str.lower()

df_vcrg_std_cor_temp_request.to_parquet(RAW_DIR / "v_crg_std_cor_temp_request.parquet",index=False)

print("Rows loaded:", len(df_vcrg_std_cor_temp_request))
print("Columns:", df_vcrg_std_cor_temp_request.columns.tolist())
print("Saved:", RAW_DIR / "v_crg_std_cor_temp_request.parquet")

display(df_vcrg_std_cor_temp_request.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24116\3476565951.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_vcrg_std_cor_temp_request = pd.read_sql(query, connection)

Rows loaded: 387
Columns: ['active', 'requirement_type_id', 'is_requestable', 'passed_prerequisites', 'status_reason_sl', 'status_reason_code', 'final_mark', 'semester_order', 'year_order', 'course_credits', 'course_name_sl', 'course_id', 'credits_count', 'credits_till_grad', 'student_id', 'std_cor_temp_request_id']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_crg_std_cor_temp_request.parquet

,active,requirement_type_id,is_requestable,passed_prerequisites,status_reason_sl,status_reason_code,final_mark,semester_order,year_order,course_credits,course_name_sl,course_id,credits_count,credits_till_grad,student_id,std_cor_temp_request_id
0,A,2.0,N,",",تم إنجاز الساعات المطلوبة لهذا النوع من المتطلبات,PASS_REQUIREMENT,NaN,1.0,2.0,2.0,لغة اجنبية حية ثانية_المانية,1038.111,6.0,43.0,21858.111,4887.0
1,A,6.0,Y,",",يمكن تسجيل المقرر,REQUESTABLE,NaN,1.0,4.0,3.0,مشكلات محاسبية معاصرة,18.111,6.0,43.0,21858.111,4888.0
2,A,5.0,Y,"1,",يمكن تسجيل المقرر,REQUESTABLE,NaN,2.0,4.0,3.0,نظرية المحاسبة,24.111,56.0,43.0,21858.111,4889.0
3,A,3.0,N,"1,",ناجح مسبقاً,SUCCESS,69.0,1.0,2.0,3.0,إدارة التسويق,98.111,48.0,43.0,21858.111,4890.0
4,A,3.0,N,"2,",ناجح مسبقاً,SUCCESS,81.0,1.0,2.0,3.0,إدارة الموارد البشرية,73.111,48.0,43.0,21858.111,4891.0

In [8]:
cursor.close()

In [8]:
cursor.close()