## setup and connect with data base

In [1]:
import oracledb
import pandas as pd
# ── SETUP ──────────────────────────────────────────────
connection = oracledb.connect(
    user="kinan",
    password="AbC@12345_+",
    host="192.168.1.203",
    port=1521,
    service_name="RAS"
)

In [2]:
cursor = connection.cursor()
pd.set_option('display.max_columns', None)

In [3]:
from pathlib import Path
import pandas as pd

# 1) Project root ثابت
PROJECT_ROOT = Path(r"D:/AI/Real projects/Academic_Advisor").resolve()

# 2) Main data folders
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PREPROCESSED_DIR = DATA_DIR / "preprocessed"
FEATURES_DIR = DATA_DIR / "features"
FINAL_DIR = DATA_DIR / "final"
REPORTS_DIR = PROJECT_ROOT / "reports"

print(PROJECT_ROOT)

D:\AI\Real projects\Academic_Advisor

In [4]:
VIEW_NAME = "RAS_USER.V_CRG_STUDENT_COURSE"

needed_columns = [
    "STUDENT_COURSE_ID",
    "STUDENT_ID",
    "COURSE_ID",
    "PART_ID",
    "GRADE_ID",
    "FINAL_MARK",
    "POINTS",
    "FINISH_STATUS",
    "COURSE_NAME_SL",
    "STUDY_MODE",
    "DEGREE_ID",
    "DEGREE_NAME_SL",
    "FACULTY_ID",
    "COURSE_CREDITS",
    "ACTIVE",
]

query = f"""
SELECT
    STUDENT_COURSE_ID,
    STUDENT_ID,
    COURSE_ID,
    PART_ID,
    GRADE_ID,
    FINAL_MARK,
    POINTS,
    FINISH_STATUS,
    COURSE_NAME_SL,
    STUDY_MODE,
    DEGREE_ID,
    DEGREE_NAME_SL,
    FACULTY_ID,
    COURSE_CREDITS,
    ACTIVE
FROM {VIEW_NAME}
WHERE ACTIVE = 'A'
  AND STUDY_MODE = 'C'
"""

df_v_crg_student_course = pd.read_sql(query, connection)
df_v_crg_student_course.columns = df_v_crg_student_course.columns.str.lower()

df_v_crg_student_course.to_parquet(RAW_DIR / "v_crg_student_course_raw.parquet",index=False)

print("Rows loaded:", len(df_v_crg_student_course))
print("Columns:", df_v_crg_student_course.columns.tolist())
print("Saved:", RAW_DIR / "v_crg_student_course_raw.parquet")
display(df_v_crg_student_course.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18124\1046808158.py:43: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_crg_student_course = pd.read_sql(query, connection)

Rows loaded: 965467
Columns: ['student_course_id', 'student_id', 'course_id', 'part_id', 'grade_id', 'final_mark', 'points', 'finish_status', 'course_name_sl', 'study_mode', 'degree_id', 'degree_name_sl', 'faculty_id', 'course_credits', 'active']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_crg_student_course_raw.parquet

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,finish_status,course_name_sl,study_mode,degree_id,degree_name_sl,faculty_id,course_credits,active
0,466289.111,1491.111,153.111,20111.0,684.111,37.0,0.00,F,التحليل الاقتصادي الجزئي,C,19.111,إدارة الأعمال,7.111,2.0,A
1,466290.111,1491.111,152.111,20111.0,684.111,48.0,0.00,F,مدخل الى القانون,C,19.111,إدارة الأعمال,7.111,2.0,A
2,466291.111,1491.111,150.111,20111.0,679.111,72.0,2.50,P,مهارات الحاسوب 1,C,19.111,إدارة الأعمال,7.111,3.0,A
3,466292.111,1491.111,149.111,20111.0,676.111,86.0,3.25,P,اللغة العربية,C,19.111,إدارة الأعمال,7.111,2.0,A
4,466293.111,1492.111,153.111,20111.0,684.111,12.0,0.00,F,التحليل الاقتصادي الجزئي,C,19.111,إدارة الأعمال,7.111,2.0,A

In [5]:
VIEW_NAME = "RAS_USER.V_ACS_GRADE"

needed_columns = [
    "GRADE_ID",
    "GRADE_VERSION_ID",
    "VERSION_TITLE_SL",
    "VERSION_NUMBER",
    "FROM_PERCENT",
    "TO_PERCENT",
    "POINTS",
    "FINISH_STATUS",
    "GRADE_SHOW",
    "FROM_SEMESTER_ID",
    "TILL_SEMESTER_ID",
    "ACTIVE",
]

query = f"""
SELECT
    GRADE_ID,
    GRADE_VERSION_ID,
    VERSION_TITLE_SL,
    VERSION_NUMBER,
    FROM_PERCENT,
    TO_PERCENT,
    POINTS,
    FROM_SEMESTER_ID,
    TILL_SEMESTER_ID,
    FINISH_STATUS,
    GRADE_SHOW,
    ACTIVE
FROM {VIEW_NAME}
WHERE ACTIVE = 'A'
"""

df_v_acs_grade = pd.read_sql(query, connection)
df_v_acs_grade.columns = df_v_acs_grade.columns.str.lower()

df_v_acs_grade.to_parquet(RAW_DIR / "v_acs_grade.parquet",index=False)

print("Rows loaded:", len(df_v_acs_grade))
print("Columns:", df_v_acs_grade.columns.tolist())
print("Saved:", RAW_DIR / "v_acs_grade.parquet")

display(df_v_acs_grade.head())

Rows loaded: 108
Columns: ['grade_id', 'grade_version_id', 'version_title_sl', 'version_number', 'from_percent', 'to_percent', 'points', 'from_semester_id', 'till_semester_id', 'finish_status', 'grade_show', 'active']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_acs_grade.parquet

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18124\4031317979.py:36: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_acs_grade = pd.read_sql(query, connection)

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
0,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
1,673.111,2.111,القرار الوزاري الموحد,2,98.0,100.0,4.00,20111.0,20162.0,P,A+,A
2,999.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.00,20051.0,20111.0,NaN,NaN,A
3,974.111,3.111,القرار رقم 230,230,98.0,100.0,4.00,20162.0,NaN,P,A+,A
4,674.111,2.111,القرار الوزاري الموحد,2,95.0,97.0,3.75,20111.0,20162.0,P,A,A

In [6]:
VIEW_NAME = "RAS_USER.V_ADD_STUDENT_DEGREE_STATUS"

needed_columns = [
    "STUDENT_ID",
    "REQUEST_ID",
    "PART_ID",
    "DEGREE_ID",
    "STUDY_MODE",
    "GPA_PERCENT",
    "GPA_POINTS",
    "END_AGPA_PERCENT",
    "END_AGPA_POINTS",
    "SEMESTER_REG_COURSES",
    "SEMESTER_REG_CREDITS",
    "SEMESTER_PASS_COURSES",
    "SEMESTER_PASS_CREDITS",
    "SEMESTER_FAIL_COURSES",
    "SEMESTER_FAIL_CREDITS",
    "TOTAL_PASS_COURSES",
    "TOTAL_PASS_CREDITS",
    "TOTAL_FAIL_COURSES",
    "TOTAL_FAIL_CREDITS",
    "REG_TOTAL_SEMESTERS",
    "FINISH_STATUS",
    "VERSION_TITLE_SL",
    "START_LEVEL_ID",
    "START_LEVEL_NAME_PL",
]

query = f"""
SELECT
    STUDENT_ID,
    REQUEST_ID,
    PART_ID,
    DEGREE_ID,
    STUDY_MODE,
    GPA_PERCENT,
    GPA_POINTS,
    END_AGPA_PERCENT,
    END_AGPA_POINTS,
    SEMESTER_REG_COURSES,
    SEMESTER_REG_CREDITS,
    SEMESTER_PASS_COURSES,  
    SEMESTER_PASS_CREDITS,
    SEMESTER_FAIL_COURSES,
    SEMESTER_FAIL_CREDITS,
    TOTAL_PASS_COURSES,
    TOTAL_PASS_CREDITS,
    TOTAL_FAIL_COURSES,
    TOTAL_FAIL_CREDITS,
    REG_TOTAL_SEMESTERS,
    FINISH_STATUS,
    VERSION_TITLE_SL,
    START_LEVEL_ID,
    START_LEVEL_NAME_PL
FROM {VIEW_NAME}
WHERE STUDY_MODE = 'C'
"""

df_v_add_student_degree_status = pd.read_sql(query, connection)
df_v_add_student_degree_status.columns = df_v_add_student_degree_status.columns.str.lower()

df_v_add_student_degree_status.to_parquet(RAW_DIR / "v_add_student_degree_status.parquet",index=False)

print("Rows loaded:", len(df_v_add_student_degree_status))
print("Columns:", df_v_add_student_degree_status.columns.tolist())
print("Saved:", RAW_DIR / "v_add_student_degree_status.parquet")

display(df_v_add_student_degree_status.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18124\1152128905.py:60: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_add_student_degree_status = pd.read_sql(query, connection)

Rows loaded: 154779
Columns: ['student_id', 'request_id', 'part_id', 'degree_id', 'study_mode', 'gpa_percent', 'gpa_points', 'end_agpa_percent', 'end_agpa_points', 'semester_reg_courses', 'semester_reg_credits', 'semester_pass_courses', 'semester_pass_credits', 'semester_fail_courses', 'semester_fail_credits', 'total_pass_courses', 'total_pass_credits', 'total_fail_courses', 'total_fail_credits', 'reg_total_semesters', 'finish_status', 'version_title_sl', 'start_level_id', 'start_level_name_pl']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_add_student_degree_status.parquet

,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
0,28401.111,570675.111,20222.0,1.111,C,84.25,3.16,86.24,3.24,8.0,21.0,7.0,20.0,0.0,0.0,5.0,14.0,0.0,0.0,2.0,NaN,القرار رقم 230,595.111,First Year
1,28401.111,550329.111,20221.0,1.111,C,89.07,3.34,89.07,3.34,5.0,14.0,5.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,595.111,First Year
2,28401.111,618048.111,20231.0,1.111,C,85.28,3.15,85.90,3.21,8.0,20.0,7.0,18.0,0.0,0.0,12.0,34.0,0.0,0.0,3.0,NaN,القرار رقم 230,596.111,Second Year
3,28401.111,648593.111,20232.0,1.111,C,85.45,3.18,85.78,3.20,9.0,20.0,9.0,20.0,0.0,0.0,19.0,52.0,0.0,0.0,4.0,NaN,القرار رقم 230,596.111,Second Year
4,28401.111,702262.111,20241.0,1.111,C,88.41,3.31,86.28,3.22,9.0,17.0,9.0,17.0,0.0,0.0,28.0,72.0,0.0,0.0,5.0,NaN,القرار رقم 230,597.111,Third year

In [7]:
VIEW_NAME = "RAS_USER.V_ACD_DEGREE_COURSE"

needed_columns = [
    "DEGREE_COURSE_ID",
    "COURSE_ID",
    "COURSE_NAME_SL",
    "DEGREE_ID",
    "DEGREE_NAME_SL",
    "YEAR_ORDER",
    "SEMESTER_ORDER",
    "COURSE_CREDITS",
    "ACTIVE",
    "CREDITS_COUNT",
    "FACULTY_ID",
    "REQUIRED_LEVEL",
    "REQUIREMENT_TYPE_SL"
    "REQ_DEGREE_ID",
]

query = f"""
SELECT
    DEGREE_COURSE_ID,
    COURSE_ID,
    COURSE_NAME_SL,
    DEGREE_ID,
    DEGREE_NAME_SL,
    YEAR_ORDER,
    SEMESTER_ORDER,
    COURSE_CREDITS,
    ACTIVE,
    CREDITS_COUNT,
    FACULTY_ID,
    REQUIRED_LEVEL,
    REQUIREMENT_TYPE_SL,
    REQ_DEGREE_ID
FROM {VIEW_NAME}
WHERE ACTIVE = 'A'
"""

df_v_acd_degree_course = pd.read_sql(query, connection)
df_v_acd_degree_course.columns = df_v_acd_degree_course.columns.str.lower()

df_v_acd_degree_course.to_parquet(RAW_DIR / "v_acd_degree_course.parquet",index=False)

print("Rows loaded:", len(df_v_acd_degree_course))
print("Columns:", df_v_acd_degree_course.columns.tolist())
print("Saved:", RAW_DIR / "v_acd_degree_course.parquet")

display(df_v_acd_degree_course.head())

Rows loaded: 1700
Columns: ['degree_course_id', 'course_id', 'course_name_sl', 'degree_id', 'degree_name_sl', 'year_order', 'semester_order', 'course_credits', 'active', 'credits_count', 'faculty_id', 'required_level', 'requirement_type_sl', 'req_degree_id']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_acd_degree_course.parquet

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18124\4150834542.py:40: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_acd_degree_course = pd.read_sql(query, connection)

,degree_course_id,course_id,course_name_sl,degree_id,degree_name_sl,year_order,semester_order,course_credits,active,credits_count,faculty_id,required_level,requirement_type_sl,req_degree_id
0,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN
1,1.111,917.111,الكيمياء الحيوية,17.111,الصيدلة,3.0,1.0,4.0,A,193.0,NaN,NaN,متطلبات الشهادة الإجبارية,17.111
2,2.111,923.111,الكيمياء الحيوية التطبيقية,17.111,الصيدلة,3.0,2.0,3.0,A,193.0,NaN,NaN,متطلبات الشهادة الإجبارية,17.111
3,3.111,908.111,الإحصاء الحيوي,17.111,الصيدلة,2.0,1.0,2.0,A,193.0,NaN,NaN,متطلبات الشهادة الإجبارية,17.111
4,4.111,891.111,البيولوجيا النباتية,17.111,الصيدلة,1.0,1.0,4.0,A,193.0,NaN,NaN,متطلبات الشهادة الإجبارية,17.111

In [8]:
VIEW_NAME = "RAS_USER.V_CRG_STUDENT_PASSED_CREDIT"

needed_columns = [
    "STUDENT_ID",
    "REQUIREMENT_TYPE_PL",
    "REQUIREMENT_TYPE_SL",
    "CREDITS_COUNT",
    "PASSED_CREDIT",
]

query = f"""
SELECT
    STUDENT_ID,
    REQUIREMENT_TYPE_PL,
    REQUIREMENT_TYPE_SL,
    CREDITS_COUNT,
    PASSED_CREDIT
FROM {VIEW_NAME}
"""

df_v_crg_student_passed_credit = pd.read_sql(query, connection)
df_v_crg_student_passed_credit.columns = df_v_crg_student_passed_credit.columns.str.lower()

df_v_crg_student_passed_credit.to_parquet(RAW_DIR / "v_crg_student_passed_credit.parquet",index=False)

print("Rows loaded:", len(df_v_crg_student_passed_credit))
print("Columns:", df_v_crg_student_passed_credit.columns.tolist())
print("Saved:", RAW_DIR / "v_crg_student_passed_credit.parquet")

display(df_v_crg_student_passed_credit.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18124\1320494628.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_crg_student_passed_credit = pd.read_sql(query, connection)

Rows loaded: 71253
Columns: ['student_id', 'requirement_type_pl', 'requirement_type_sl', 'credits_count', 'passed_credit']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_crg_student_passed_credit.parquet

,student_id,requirement_type_pl,requirement_type_sl,credits_count,passed_credit
0,2726.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,22.0
1,2729.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,45.0
2,2735.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,196.0
3,2760.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,185.0
4,2854.111,Mandatory Degree Requirements,متطلبات الشهادة الإجبارية,193.0,35.0

In [10]:
VIEW_NAME = "RAS_USER.V_SCH_COURSE_OFFER"

needed_columns = [
    "COURSE_ID",
    "COURSE_CREDITS",
    "PART_ID",
    "DEPARTMENT_ID",
    "FACULTY_ID",
    "ALLOW_REGISTER",
]

query = f"""
SELECT
    COURSE_ID,
    COURSE_CREDITS,
    PART_ID,
    DEPARTMENT_ID,
    FACULTY_ID,
    ALLOW_REGISTER
FROM {VIEW_NAME}
"""

df_v_sch_course_offers = pd.read_sql(query, connection)
df_v_sch_course_offers.columns = df_v_sch_course_offers.columns.str.lower()

df_v_sch_course_offers.to_parquet(RAW_DIR / "v_sch_course_offers.parquet",index=False)

print("Rows loaded:", len(df_v_sch_course_offers))
print("Columns:", df_v_sch_course_offers.columns.tolist())
print("Saved:", RAW_DIR / "v_sch_course_offers.parquet")

display(df_v_sch_course_offers.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18124\2949394349.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v_sch_course_offers = pd.read_sql(query, connection)

Rows loaded: 137899
Columns: ['course_id', 'course_credits', 'part_id', 'department_id', 'faculty_id', 'allow_register']
Saved: D:\AI\Real projects\Academic_Advisor\data\raw\v_sch_course_offers.parquet

,course_id,course_credits,part_id,department_id,faculty_id,allow_register
0,88.111,3.0,20050.0,37.111,7.111,NaN
1,88.111,3.0,20051.0,37.111,7.111,NaN
2,88.111,3.0,20052.0,37.111,7.111,NaN
3,88.111,3.0,20053.0,37.111,7.111,NaN
4,88.111,3.0,20060.0,37.111,7.111,NaN

In [11]:
cursor.close()