In [2]:
import pandas as pd 
df=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_add_student_degree_status_clean.parquet")
pd.set_option("display.max_columns", None)

In [63]:
df.describe()

,part_id,part_year,part_semester_no,gpa_percent,gpa_points,start_part_id,start_part_year,start_part_semester_no,finish_part_id,finish_part_year,finish_part_semester_no,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters
count,154768.0,154768.0,154768.0,154768.0,154768.0,154763.0,154763.0,154763.0,107879.0,107879.0,107879.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154768.0,154162.0
mean,20192.223263,2019.033528,1.887987,56.519266,1.808421,20167.982677,2016.68654,1.117276,20207.811326,2020.592571,1.885613,59.20631,1.947342,64.134566,2.115224,4.589146,12.939535,3.557363,10.027305,0.652544,1.861309,27.673744,78.400102,7.142568,20.660363,8.235421
std,35.020266,3.510157,0.858061,26.146758,1.052316,33.066528,3.30572,0.340351,30.030378,3.006012,0.820516,22.860714,0.877536,16.142495,0.706645,2.378229,6.693185,2.46903,6.977219,1.18661,3.504629,21.029037,62.213661,11.772033,36.086469,5.993601
min,20051.0,2005.0,1.0,0.0,0.0,20051.0,2005.0,1.0,20061.0,2006.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,20164.0,2016.0,1.0,50.0,1.08,20141.0,2014.0,1.0,20191.0,2019.0,1.0,58.41,1.72,60.94,1.89,3.0,8.0,1.0,4.0,0.0,0.0,10.0,26.0,0.0,0.0,3.0
50%,20201.0,2020.0,2.0,63.94,2.05,20171.0,2017.0,1.0,20213.0,2021.0,2.0,64.94,2.13,65.98,2.19,5.0,15.0,4.0,10.0,0.0,0.0,25.0,68.0,3.0,8.0,7.0
75%,20221.0,2022.0,3.0,74.0,2.61,20201.0,2020.0,1.0,20232.0,2023.0,2.0,71.63,2.49,72.58,2.54,6.0,18.0,6.0,16.0,1.0,3.0,43.0,122.0,9.0,26.0,12.0
max,20254.0,2025.0,4.0,100.0,4.0,20242.0,2024.0,4.0,20251.0,2025.0,4.0,99.78,4.0,99.78,4.0,17.0,72.5,13.0,49.0,17.0,66.5,106.0,334.0,193.0,713.5,49.0

In [ ]:
add=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_add_student_degree_status.parquet")

In [ ]:
add.head()

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
0,340275.111,28401.111,570675.111,20222.0,1.111,C,84.25,3.16,20221.0,NaN,89.07,3.34,86.24,3.24,8.0,21.0,7.0,20.0,0.0,0.0,5.0,14.0,0.0,0.0,2.0,NaN,القرار رقم 230,595.111,First Year
1,334725.111,28401.111,550329.111,20221.0,1.111,C,89.07,3.34,20221.0,NaN,0.00,0.00,89.07,3.34,5.0,14.0,5.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,595.111,First Year
2,353697.111,28401.111,618048.111,20231.0,1.111,C,85.28,3.15,20221.0,NaN,86.24,3.24,85.90,3.21,8.0,20.0,7.0,18.0,0.0,0.0,12.0,34.0,0.0,0.0,3.0,NaN,القرار رقم 230,596.111,Second Year
3,361412.111,28401.111,648593.111,20232.0,1.111,C,85.45,3.18,20221.0,NaN,85.90,3.21,85.78,3.20,9.0,20.0,9.0,20.0,0.0,0.0,19.0,52.0,0.0,0.0,4.0,NaN,القرار رقم 230,596.111,Second Year
4,374249.111,28401.111,702262.111,20241.0,1.111,C,88.41,3.31,20221.0,NaN,85.78,3.20,86.28,3.22,9.0,17.0,9.0,17.0,0.0,0.0,28.0,72.0,0.0,0.0,5.0,NaN,القرار رقم 230,597.111,Third year

In [ ]:
d=add.describe()
d.to_csv(r"D:\AI\Real projects\Academic_Advisor\decribe.csv")

In [56]:
d

,student_status_id,student_id,request_id,part_id,degree_id,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,start_level_id
count,154779.000000,154779.000000,146661.000000,154779.000000,152653.000000,154768.000000,154768.000000,154774.000000,107879.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154768.000000,154162.000000,152660.000000
mean,278818.125847,12619.951120,343303.190604,20192.225308,7.731702,56.519266,1.808421,20167.986445,20207.811326,59.206310,1.947342,64.134566,2.115224,4.589146,12.939535,3.557363,10.027305,0.652544,1.861309,27.673744,78.400102,7.142568,20.660363,8.235421,475.624003
std,70557.472276,6133.201133,224592.506891,35.019862,7.166146,26.146758,1.052316,33.068373,30.030378,22.860714,0.877536,16.142495,0.706645,2.378229,6.693185,2.469030,6.977219,1.186610,3.504629,21.029037,62.213661,11.772033,36.086469,5.993601,219.168329
min,113278.111000,48.111000,7157.111000,20051.000000,1.111000,0.000000,0.000000,20051.000000,20061.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.111000
25%,236841.611000,9365.111000,146497.111000,20164.000000,2.111000,50.000000,1.080000,20141.000000,20191.000000,58.410000,1.720000,60.940000,1.890000,3.000000,8.000000,1.000000,4.000000,0.000000,0.000000,10.000000,26.000000,0.000000,0.000000,3.000000,291.111000
50%,286820.111000,11940.111000,271619.111000,20201.000000,3.111000,63.940000,2.050000,20171.000000,20213.000000,64.940000,2.130000,65.980000,2.190000,5.000000,15.000000,4.000000,10.000000,0.000000,0.000000,25.000000,68.000000,3.000000,8.000000,7.000000,582.111000
75%,330925.611000,14938.111000,538037.111000,20221.000000,13.111000,74.000000,2.610000,20201.000000,20232.000000,71.630000,2.490000,72.580000,2.540000,6.000000,18.000000,6.000000,16.000000,1.000000,3.000000,43.000000,122.000000,9.000000,26.000000,12.000000,631.111000
max,403812.111000,28890.111000,844441.000000,20254.000000,24.111000,100.000000,4.000000,20242.000000,20251.000000,99.780000,4.000000,99.780000,4.000000,17.000000,72.500000,13.000000,49.000000,17.000000,66.500000,106.000000,334.000000,193.000000,713.500000,49.000000,862.111000

In [ ]:
df1[df1['semester_pass_credits'].eq(49.000000)]

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
91521,342705.111,11015.111,577073.111,20222.0,2.111,C,62.0,2.1,20161.0,20222.0,64.4,2.22,65.6,2.28,7.0,49.0,7.0,49.0,0.0,0.0,63.0,228.0,14.0,54.0,18.0,GRADUATED,القرار رقم 230,557.111,Sixth Year

In [11]:
df1[df1['semester_reg_credits'].eq(72.500000)]

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
88105,236604.111,3472.111,141352.111,20164.0,2.111,C,34.37,0.12,20131.0,NaN,48.5,0.95,49.92,1.01,16.0,72.5,1.0,6.0,15.0,66.5,46.0,152.5,81.0,333.0,26.0,NaN,القرار رقم 230,282.111,Fifth year

In [18]:
df2=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_crg_student_course_raw.parquet")
test=df2[(df2['student_id'].eq(3472.111))&(df2['part_id'].eq(20164.0))]

In [52]:
test.to_csv(r"D:\AI\Real projects\Academic_Advisor\test.csv")

In [21]:
test1=df2[(df2['student_id'].eq(11015.111))&(df2['part_id'].eq(20222.0))]

In [53]:
test1.to_csv(r"D:\AI\Real projects\Academic_Advisor\test1.csv")

In [23]:
df1[df1['total_fail_credits'].eq(713.500000)]

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
88078,301185.111,3470.111,334312.111,20203.0,2.111,C,59.50,1.88,20161.0,20232.0,58.26,1.57,60.00,1.70,2.0,8.0,2.0,8.0,0.0,0.0,71.0,231.5,193.0,713.5,43.0,GRADUATED,القرار رقم 230,557.111,Sixth Year
88079,321187.111,3470.111,517663.111,20213.0,2.111,C,99.00,4.00,20161.0,20232.0,63.26,2.06,64.19,2.11,1.0,3.0,1.0,3.0,0.0,0.0,76.0,257.5,193.0,713.5,46.0,GRADUATED,القرار رقم 230,557.111,Sixth Year
88080,358127.111,3470.111,NaN,20231.0,2.111,C,0.00,0.00,20161.0,20232.0,64.19,2.11,64.19,2.11,0.0,0.0,0.0,0.0,0.0,0.0,77.0,260.5,193.0,713.5,48.0,GRADUATED,القرار رقم 230,557.111,Sixth Year
88083,308846.111,3470.111,347651.111,20211.0,2.111,C,66.67,2.25,20161.0,20232.0,60.00,1.70,63.26,2.06,3.0,18.0,3.0,18.0,0.0,0.0,73.0,239.5,193.0,713.5,44.0,GRADUATED,القرار رقم 230,557.111,Sixth Year
88084,315139.111,3470.111,455891.111,20212.0,2.111,C,0.00,0.00,20161.0,20232.0,63.26,2.06,63.26,2.06,5.0,12.0,0.0,0.0,0.0,0.0,76.0,257.5,193.0,713.5,45.0,GRADUATED,القرار رقم 230,557.111,Sixth Year
88085,330847.111,3470.111,537520.111,20221.0,2.111,C,0.00,0.00,20161.0,20232.0,64.19,2.11,64.19,2.11,4.0,12.0,0.0,0.0,0.0,0.0,77.0,260.5,193.0,713.5,47.0,GRADUATED,القرار رقم 230,557.111,Sixth Year
88086,371794.111,3470.111,NaN,20232.0,2.111,C,80.00,3.00,20161.0,20232.0,62.20,2.11,65.40,2.27,1.0,24.0,1.0,24.0,0.0,0.0,77.0,260.5,193.0,713.5,49.0,GRADUATED,القرار رقم 230,557.111,Sixth Year

In [62]:
test2=df2[(df2['student_id'].eq(3470.111))&(df2['finish_status'].eq('F'))]
test2

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,finish_status,course_name_sl,register_status,study_mode,degree_id,degree_name_sl,faculty_id,course_credits,active
132382,988015.111,3470.111,699.111,20161.0,985.111,42.0,0.0,F,الطب الباطني (5),R,C,2.111,دكتور في الطب,2.111,6.0,A
132383,988016.111,3470.111,698.111,20161.0,985.111,34.0,0.0,F,الطب الباطني (4),R,C,2.111,دكتور في الطب,2.111,6.0,A
137076,988115.111,3470.111,711.111,20161.0,985.111,45.0,0.0,F,الجراحة (4),R,C,2.111,دكتور في الطب,2.111,5.0,A
154623,1048134.111,3470.111,711.111,20164.0,985.111,42.0,0.0,F,الجراحة (4),E,C,2.111,دكتور في الطب,2.111,5.0,A
154624,1048135.111,3470.111,698.111,20164.0,985.111,43.0,0.0,F,الطب الباطني (4),E,C,2.111,دكتور في الطب,2.111,6.0,A
154625,1048136.111,3470.111,699.111,20164.0,985.111,45.0,0.0,F,الطب الباطني (5),E,C,2.111,دكتور في الطب,2.111,6.0,A
154626,1048138.111,3470.111,665.111,20164.0,985.111,42.0,0.0,F,علم المصطلحات الطبية,E,C,2.111,دكتور في الطب,2.111,2.0,A
188099,1039920.111,3470.111,665.111,20163.0,985.111,32.0,0.0,F,علم المصطلحات الطبية,R,C,2.111,دكتور في الطب,2.111,2.0,A
232269,1082977.111,3470.111,704.111,20171.0,985.111,47.0,0.0,F,أمراض الأطفال (1),R,C,2.111,دكتور في الطب,2.111,4.5,A
241454,1082883.111,3470.111,709.111,20171.0,985.111,33.0,0.0,F,جراحة (2),R,C,2.111,دكتور في الطب,2.111,6.0,A
241455,1082884.111,3470.111,696.111,20171.0,985.111,32.0,0.0,F,الطب الباطني (2),R,C,2.111,دكتور في الطب,2.111,6.0,A
252554,1120635.111,3470.111,697.111,20172.0,985.111,31.0,0.0,F,الطب الباطني (3),R,C,2.111,دكتور في الطب,2.111,6.0,A
255777,1116501.111,3470.111,706.111,20172.0,985.111,39.0,0.0,F,أمراض الأطفال (2),R,C,2.111,دكتور في الطب,2.111,5.0,A
257833,1225277.111,3470.111,690.111,20183.0,985.111,21.0,0.0,F,الأحياء الدقيقة (2),R,C,2.111,دكتور في الطب,2.111,4.0,A
263787,1204793.111,3470.111,678.111,20182.0,985.111,46.0,0.0,F,الكيمياء السريرية,R,C,2.111,دكتور في الطب,2.111,2.0,A
272419,1133375.111,3470.111,678.111,20173.0,985.111,38.0,0.0,F,الكيمياء السريرية,R,C,2.111,دكتور في الطب,2.111,2.0,A
294086,1168128.111,3470.111,696.111,20181.0,985.111,36.0,0.0,F,الطب الباطني (2),R,C,2.111,دكتور في الطب,2.111,6.0,A
294087,1168129.111,3470.111,699.111,20181.0,985.111,40.0,0.0,F,الطب الباطني (5),R,C,2.111,دكتور في الطب,2.111,6.0,A
294088,1168130.111,3470.111,709.111,20181.0,985.111,47.0,0.0,F,جراحة (2),R,C,2.111,دكتور في الطب,2.111,6.0,A
303114,1130277.111,3470.111,689.111,20173.0,985.111,21.0,0.0,F,الأحياء الدقيقة (1),R,C,2.111,دكتور في الطب,2.111,4.0,A
322628,1225079.111,3470.111,689.111,20183.0,985.111,35.0,0.0,F,الأحياء الدقيقة (1),R,C,2.111,دكتور في الطب,2.111,4.0,A
329097,1286923.111,3470.111,696.111,20192.0,985.111,46.0,0.0,F,الطب الباطني (2),R,C,2.111,دكتور في الطب,2.111,6.0,A
329098,1286925.111,3470.111,699.111,20192.0,985.111,44.0,0.0,F,الطب الباطني (5),R,C,2.111,دكتور في الطب,2.111,6.0,A
329099,1286926.111,3470.111,709.111,20192.0,985.111,46.0,0.0,F,جراحة (2),R,C,2.111,دكتور في الطب,2.111,6.0,A
359024,1276819.111,3470.111,689.111,20191.0,985.111,32.0,0.0,F,الأحياء الدقيقة (1),R,C,2.111,دكتور في الطب,2.111,4.0,A
362821,1276816.111,3470.111,698.111,20191.0,985.111,43.0,0.0,F,الطب الباطني (4),R,C,2.111,دكتور في الطب,2.111,6.0,A
362823,1276818.111,3470.111,709.111,20191.0,985.111,40.0,0.0,F,جراحة (2),R,C,2.111,دكتور في الطب,2.111,6.0,A
376536,1331943.111,3470.111,689.111,20193.0,985.111,36.0,0.0,F,الأحياء الدقيقة (1),R,C,2.111,دكتور في الطب,2.111,4.0,A
376537,1331944.111,3470.111,690.111,20193.0,985.111,34.0,0.0,F,الأحياء الدقيقة (2),R,C,2.111,دكتور في الطب,2.111,4.0,A
414119,1457609.111,3470.111,690.111,20201.0,985.111,33.0,0.0,F,الأحياء الدقيقة (2),R,C,2.111,دكتور في الطب,2.111,4.0,A
446242,1463230.111,3470.111,696.111,20202.0,985.111,30.0,0.0,F,الطب الباطني (2),R,C,2.111,دكتور في الطب,2.111,6.0,A
446244,1463232.111,3470.111,699.111,20202.0,985.111,46.0,0.0,F,الطب الباطني (5),R,C,2.111,دكتور في الطب,2.111,6.0,A
505179,1409459.111,3470.111,699.111,20201.0,985.111,46.0,0.0,F,الطب الباطني (5),R,C,2.111,دكتور في الطب,2.111,6.0,A

In [44]:
test2['active'].value_counts()

active
A    33
Name: count, dtype: int64

In [54]:
test2.to_csv(r"D:\AI\Real projects\Academic_Advisor\test2.csv")

In [45]:
df[df['semester_fail_credits'].eq(66.500000)]

,student_status_id,student_id,part_id,part_year,part_semester_no,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,start_part_year,start_part_semester_no,finish_part_id,finish_part_year,finish_part_semester_no,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,reg_total_semesters_status,finish_status,version_title_sl,start_level_id,start_level_name_pl,flag_is_finished,flag_missing_finish_part_id,flag_missing_finish_status,flag_missing_degree_id,flag_registered_without_degree_or_courses_candidate,flag_missing_reg_total_semesters,flag_invalid_part_id,flag_invalid_start_part_id,flag_invalid_finish_part_id
88104,236604.111,3472.111,20164,2016,4,2.111,C,34.37,0.12,20131,2013,1,<NA>,<NA>,<NA>,48.5,0.95,49.92,1.01,16,72.5,1,6.0,15,66.5,46,152.5,81,333.0,26,known,<NA>,القرار رقم 230,282.111,Fifth year,False,True,True,False,False,False,False,False,False

In [47]:
test3=df2[(df2['student_id'].eq(3472.111))&(df2['part_id'].eq(20164))]

In [55]:
test3.to_csv(r"D:\AI\Real projects\Academic_Advisor\test3.csv")

In [60]:

test3[test3['course_id'].eq(676.111)]

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,finish_status,course_name_sl,register_status,study_mode,degree_id,degree_name_sl,faculty_id,course_credits,active
168769,1049771.111,3472.111,676.111,20164.0,985.111,31.0,0.0,F,الكيمياء الحيوية الطبية (1),E,C,2.111,دكتور في الطب,2.111,5.0,A
176159,1048688.111,3472.111,676.111,20164.0,NaN,NaN,NaN,NaN,الكيمياء الحيوية الطبية (1),D,C,2.111,دكتور في الطب,2.111,5.0,A

In [3]:
df=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\audit\V_ADD_STUDENT_DEGREE_STATUS\isolated_status_rows_v1.parquet")

In [4]:
a=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_crg_student_course_raw.parquet")

In [5]:
b=a['student_id'].unique()
len(b)

16686

In [6]:
add_student=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_add_student_degree_status.parquet")
b=add_student['student_id'].unique()
len(b)

14516

In [ ]:
df=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_add_student_degree_status_clean.parquet")