In [10]:
import pandas as pd
pd.set_option('display.max_columns', 50)

In [11]:
df_row=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_add_student_degree_status.parquet")

In [ ]:
df_row.head()

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
0,334725.111,28401.111,550329.111,20221.0,1.111,C,89.07,3.34,20221.0,NaN,0.00,0.00,89.07,3.34,5.0,14.0,5.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,595.111,First Year
1,340275.111,28401.111,570675.111,20222.0,1.111,C,84.25,3.16,20221.0,NaN,89.07,3.34,86.24,3.24,8.0,21.0,7.0,20.0,0.0,0.0,5.0,14.0,0.0,0.0,2.0,NaN,القرار رقم 230,595.111,First Year
2,353697.111,28401.111,618048.111,20231.0,1.111,C,85.28,3.15,20221.0,NaN,86.24,3.24,85.90,3.21,8.0,20.0,7.0,18.0,0.0,0.0,12.0,34.0,0.0,0.0,3.0,NaN,القرار رقم 230,596.111,Second Year
3,361412.111,28401.111,648593.111,20232.0,1.111,C,85.45,3.18,20221.0,NaN,85.90,3.21,85.78,3.20,9.0,20.0,9.0,20.0,0.0,0.0,19.0,52.0,0.0,0.0,4.0,NaN,القرار رقم 230,596.111,Second Year
4,374249.111,28401.111,702262.111,20241.0,1.111,C,88.41,3.31,20221.0,NaN,85.78,3.20,86.28,3.22,9.0,17.0,9.0,17.0,0.0,0.0,28.0,72.0,0.0,0.0,5.0,NaN,القرار رقم 230,597.111,Third year

In [13]:
df_row.info()

<class 'pandas.DataFrame'>
RangeIndex: 154779 entries, 0 to 154778
Data columns (total 29 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   student_status_id      154779 non-null  float64
 1   student_id             154779 non-null  float64
 2   request_id             146661 non-null  float64
 3   part_id                154779 non-null  float64
 4   degree_id              152653 non-null  float64
 5   study_mode             154779 non-null  str
 6   gpa_percent            154768 non-null  float64
 7   gpa_points             154768 non-null  float64
 8   start_part_id          154774 non-null  float64
 9   finish_part_id         107879 non-null  float64
 10  start_agpa_percent     154768 non-null  float64
 11  start_agpa_points      154768 non-null  float64
 12  end_agpa_percent       154768 non-null  float64
 13  end_agpa_points        154768 non-null  float64
 14  semester_reg_courses   154768 non-null  float64
 15  semester_reg_credits   154768 non-null  float64
 16  semester_pass_courses  154768 non-null  float64
 17  semester_pass_credits  154768 non-null  float64
 18  semester_fail_courses  154768 non-null  float64
 19  semester_fail_credits  154768 non-null  float64
 20  total_pass_courses     154768 non-null  float64
 21  total_pass_credits     154768 non-null  float64
 22  total_fail_courses     154768 non-null  float64
 23  total_fail_credits     154768 non-null  float64
 24  reg_total_semesters    154162 non-null  float64
 25  finish_status          108171 non-null  str
 26  version_title_sl       154768 non-null  str
 27  start_level_id         152660 non-null  float64
 28  start_level_name_pl    154779 non-null  str
dtypes: float64(25), str(4)
memory usage: 40.4 MB

In [14]:
df_row.isna().sum()

student_status_id            0
student_id                   0
request_id                8118
part_id                      0
degree_id                 2126
study_mode                   0
gpa_percent                 11
gpa_points                  11
start_part_id                5
finish_part_id           46900
start_agpa_percent          11
start_agpa_points           11
end_agpa_percent            11
end_agpa_points             11
semester_reg_courses        11
semester_reg_credits        11
semester_pass_courses       11
semester_pass_credits       11
semester_fail_courses       11
semester_fail_credits       11
total_pass_courses          11
total_pass_credits          11
total_fail_courses          11
total_fail_credits          11
reg_total_semesters        617
finish_status            46608
version_title_sl            11
start_level_id            2119
start_level_name_pl          0
dtype: int64

In [15]:
df_row=df_row[df_row['gpa_percent'].notnull()]

In [16]:
df_row.isna().sum()

student_status_id            0
student_id                   0
request_id                8107
part_id                      0
degree_id                 2115
study_mode                   0
gpa_percent                  0
gpa_points                   0
start_part_id                5
finish_part_id           46889
start_agpa_percent           0
start_agpa_points            0
end_agpa_percent             0
end_agpa_points              0
semester_reg_courses         0
semester_reg_credits         0
semester_pass_courses        0
semester_pass_credits        0
semester_fail_courses        0
semester_fail_credits        0
total_pass_courses           0
total_pass_credits           0
total_fail_courses           0
total_fail_credits           0
reg_total_semesters        606
finish_status            46597
version_title_sl             0
start_level_id            2108
start_level_name_pl          0
dtype: int64

In [17]:
df_row['finish_status'].value_counts()

finish_status
GRADUATED                  87832
CLOSE_FILE                 13275
WITHDRAWN                   3559
CHANGE_PLAN                 1885
CANCEL_ADMISSION             588
FINAL_DISMISS                516
CHANGE_DEGREE                287
CHANGE_FACULTY               225
COMPARISON_UNDERAPPLIED        4
Name: count, dtype: int64

In [18]:
df_row[df_row['finish_status'].eq("GRADUATED")]

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
960,155347.111,10000.111,36525.111,20151.0,3.111,C,68.20,2.41,20151.0,20191.0,0.00,0.00,68.20,2.41,6.0,17.0,6.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,GRADUATED,القرار رقم 230,205.111,First Year
961,155348.111,10000.111,36526.111,20152.0,3.111,C,67.20,2.36,20151.0,20191.0,68.20,2.41,67.80,2.39,6.0,18.0,6.0,18.0,0.0,0.0,6.0,17.0,0.0,0.0,2.0,GRADUATED,القرار رقم 230,205.111,First Year
962,155349.111,10000.111,36527.111,20153.0,3.111,C,65.00,2.25,20151.0,20191.0,67.80,2.39,67.20,2.36,3.0,9.0,3.0,9.0,0.0,0.0,12.0,35.0,0.0,0.0,3.0,GRADUATED,القرار رقم 230,206.111,Second Year
963,155350.111,10000.111,36528.111,20161.0,3.111,C,64.40,2.22,20151.0,20191.0,67.20,2.36,66.40,2.32,6.0,18.0,6.0,18.0,0.0,0.0,15.0,44.0,0.0,0.0,4.0,GRADUATED,القرار رقم 230,206.111,Second Year
964,177896.111,10000.111,127746.111,20162.0,3.111,C,63.40,2.17,20151.0,20191.0,66.40,2.32,65.60,2.28,6.0,18.0,6.0,18.0,0.0,0.0,21.0,62.0,0.0,0.0,5.0,GRADUATED,القرار رقم 230,206.111,Second Year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154744,338495.111,16029.111,566750.111,20222.0,11.111,C,77.21,2.71,20201.0,20242.0,68.18,2.31,69.65,2.38,6.0,17.0,5.0,14.0,0.0,0.0,32.0,79.0,4.0,11.0,8.0,GRADUATED,القرار رقم 230,706.111,Second Year
154745,352418.111,16029.111,615883.111,20231.0,11.111,C,65.76,1.94,20201.0,20242.0,69.65,2.38,69.01,2.31,6.0,17.0,4.0,13.0,2.0,4.0,37.0,93.0,4.0,11.0,9.0,GRADUATED,القرار رقم 230,707.111,Third year
154746,360874.111,16029.111,647914.111,20232.0,11.111,C,68.18,1.96,20201.0,20242.0,69.01,2.31,69.38,2.29,6.0,17.0,4.0,11.0,2.0,6.0,41.0,106.0,6.0,15.0,10.0,GRADUATED,القرار رقم 230,707.111,Third year
154747,373095.111,16029.111,697778.111,20241.0,11.111,C,62.00,1.59,20201.0,20242.0,69.38,2.29,69.99,2.34,6.0,17.0,4.0,12.0,1.0,2.0,45.0,117.0,8.0,21.0,11.0,GRADUATED,القرار رقم 230,708.111,Fourth Year
154748,380611.111,16029.111,734398.111,20242.0,11.111,C,72.00,2.60,20201.0,20242.0,66.80,2.34,68.00,2.40,4.0,12.0,4.0,12.0,0.0,0.0,49.0,129.0,9.0,23.0,12.0,GRADUATED,القرار رقم 230,708.111,Fourth Year